### ISSUE TITLE
Sharing Issue

### ISSUE THREAD

**Issue by mngsnke** [saros-project/saros#1053]
One of my collaborators tried joining but it says "...does not support Saros."

I also noticed that his logo in the friends list is yellow, unlike some of my friends which is blue?

Can you help me with my issue?

**Comment by srossbach** [comment]
What is the version of the collaborator ? We made some changes in such way that you do not get a confirmation if the version is too old when using Saros/E 16.0.0 and trying to invite someone with a lower version. That maybe the reason that your collaborator is shown as pure yellow which is normally only used when a contact is using an XMPP messenger.
