### ISSUE TITLE
Saros Service is down

### ISSUE THREAD

**Issue by J0NASLP** [saros-project/saros#1054]
I can't connect to Saros anymore. Yesterday it worked perfectly and I haven't changed any settings. I am connected to the internet.
If I startup Eclipse, this error message appears:
<https://cdn.discordapp.com/attachments/424182861768294400/727862483842498651/unknown.png>
For the other participant it's the same thing. Restarting Eclipse or reconnecting doesn't help.
@saros-infrastructure

**Comment by chaosflo44-plus** [comment]
@saros-infrastructure #bootsaros

**Comment by tobous** [comment]
This is due to a forced restart of our server in the university network to install an update. I am working on restoring the XMPP server.

**Comment by chaosflo44-plus** [comment]
Oh. We needed to update our Saros clients yesterday. Sorry, we didn't know it. Then I guess we are going to wait?

**Comment by srossbach** [comment]
Just for your information, you can use mostly any XMPP server or just host your own. You should not expect that our service is running all the time and there is likely never an announcement when it is taken down for what reason ever.

**Comment by chaosflo44-plus** [comment]
I think it is complicated and timewasting to create a Server just for coding when we can use another one

**Comment by tobous** [comment]
Ok, the server is running again and seems to be functioning correctly for me. Sorry for the inconvenience.

If there are any further issue for you, please say so.

> Just for your information, you can use mostly any XMPP server or just host your own. You should not expect that our service is running all the time and there is likely never an announcement when it is taken down for what reason ever.

While it is true that Saros does not require our own XMPP server, offering it is still a huge usability improvement as the user is not forced to set up their own XMPP server or use a different public one that might not be configured correctly (or might look unfavorably on the potentially heavy traffic created by Saros). So trying to still offer good coverage/availability for our XMPP server is something we should still aspire to.

The current solution hosting it at the university is not optimal as we are still having issues with the general setup and the technical support infrastructure, but we have not found a better alternative.

**Comment by srossbach** [comment]
Maybe we should replace XMPP with Discord 😉

**Comment by J0NASLP** [comment]
Saros is down again :/

**Comment by chaosflo44-plus** [comment]
Yes, we should replace it 😂.
But Saros is down again :E

**Comment by tobous** [comment]
> Yes, we should replace it .
> But Saros is down again :E

I'm working on it.

**Comment by tobous** [comment]
The server is up and running again.
