### ISSUE TITLE
Deal with current Gerrit changes before migration to GitHub

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#113]
Gerrit changes that are still current (meaning they are being actively worked) should be dealt with before the migration to GitHub as our review system on July 16th.

As we are not planning on shutting down our Gerrit server in the near future (we are just making it read-only), it is not an absolute necessity to deal with all relevant open changes now. But we would still prefer to do as much of the migration as possible right now as it only gets harder the longer we wait after the migration.

Current contributers without a known GitHub account:
- Oliver Hanßen
- Sabine Bender
- Stefan Rossbach

### Current Changes

Current changes should
- either be merged before the migration (if their review process concluded in time)
- or be manually converted into a GitHub pull request (if a complete review is not feasible before the 16th of July). These migrated pull requests should link to the original Gerrit change if it contains any relevant review/change history.

Please add such changes to a list with your name in the section **List of Current Gerrit Changes**. If you have the time, please also consider doing some reviews for the changes  listed by other developers to reduce the general migration efforts. (However, this does not mean that you should rush the reviews. The code quality should not suffer as a result of this migration.)

### Old Changes

If there are also older changes that might still be useful as a basis for future work but that won't be worked on in the immediate future, it probably isn't useful to create a pull request right away. Please add these changes to the list **List of Old Gerrit Changes That Might Still Be Useful** or directly create a GitHub issue for them.

#### List of Current Gerrit Changes

The following lists contain the Gerrit changes the corresponding developers deem as current. If one of your listed changes got merged or migrated, please mark it as done on the list.

##### @tobous
- [x]  [[INTERNAL][I] Add a converter for VirtualFiles](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3558/)
- [x] [[INTERNAL][I] Add AnnotationRange](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3593/)
- [x] [[INTERNAL][I] Add AbstractEditorAnnotation](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3565/)
- [x] [[INTERNAL][I] Add implementations for text annotation](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3594/)
- [x] [[INTERNAL][I] Add AnnotationStore](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3567/)
- [x] [[INTERNAL][I] Add AnnotationManager](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3595/)
- [x] [[INTERNAL][I] Add utility methods to AnnotationManager](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3568/)
- [x] [[INTERNAL][I] Add AnnotationManager#addSelectionAnnotation(...)](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3569/)
- [x] [[INTERNAL][I] Add AnnotationManager#addContributionAnnotation(...)](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3570/)
- [x] [[INTERNAL][I] Add AnnotationManager#moveAnnotationsAfterAddition(...)](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3571/)
- [x] [[INTERNAL][I] Add AnnotationManager#moveAnnotationsAfterDeletion(...)](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3572/)
- [x] [[INTERNAL][I] Add AnnotationManager#addAnnotationsToOpenedEditor(...)](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3573/)
- [x] [[INTERNAL][I] Add AnnotationManager#updateAnnotationStore(...)](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3574/)
- [x] [[INTERNAL][I] Add removal methods to AnnotationManger](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3575/)
- [x] [[INTERNAL][I] Use AnnotationManager to add contribution annotations](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3576/)
- [x] [[INTERNAL][I] Use AnnotationManager to add SelectionAnnotations](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3577/)
- [x] [[INTERNAL][I] Display held annotations when editor is opened](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3579/)
- [x] [[INTERNAL][I] Add BeforeEditorActionListener](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3580/)

##### @Drakulix
- [x] [[FEATURE][CORE] Introduce project transferType](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3520/)
- [x] [[FEATURE][CORE] Abstract ProjectNegotiation](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3561/)

##### @m273d15
- [x] [[BUILD] Deploy master branch nightly to GitHub Releases](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3588/)

##### @jafey
- [x] [[STF] Add RemoteHTMLInputField and use it in AddContactTest](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3493/)
- [x] [[STF] Open HTML view via SarosApi and InputField improvement](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3539)
- [x] [[STF] Added ComponentTestView for HTML component testing](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3540)
- [x] [[STF] Add RemoteHTMLCheckbox and RemoteHTMLRadioGroup](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3546)
- [x] [[STF] Add RemoteHTMLSelect and RemoteHTMLMultiSelect](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3547)
- [x] [[STF] Add RemoteHTMLProgressBar](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3548)
- [x] [[STF] Add RemoteHTMLTextElement to test functionality of buttons](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3583)
- [x] [[STF][RREFACTOR] Extract view enum](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3584)
- [x] [[STF] Add StartSessionWizardTest](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3585)
- [x] [[UI][FIX] Set size of EclipseBrowserDialog](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3586)
- [x] [[STF][REFACTOR] remove duplicate code, move/rename test and packages](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3592)
- [x] [[FEATURE][HTML] Implement Configuration Wizard UI (Marius Schidlack)](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3375)
- [x] [[FEATURE][HTML] Create browser page for configuration wizard (Marius Schidlack)](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3355)
- [x] [[FEATURE][HTML] Implement 'Rename' and 'Delete' operations for contacts (Marius Schidlack)](https://saros-build.imp.fu-berlin.de/gerrit/#/c/3377/)

#### List of Old Gerrit Changes That Might Still Be Useful

- [ ] [[FEATURE] Make it possible for non-hosts to add projects](https://saros-build.imp.fu-berlin.de/gerrit/#/c/2264/)

**Comment by jafey** [comment]
I can't edit the issue.

**Comment by jafey** [comment]
No, there is no edit button or pen icon. I can't tick the checkboxes either.

![screen](https://user-images.githubusercontent.com/23552401/42375373-aa1ed1ca-811b-11e8-9f10-7a3dfbe14d53.PNG)

**Comment by tobous** [comment]
Ok, then please post a comment with changes you would like me to add to your list and I will add them to the main comment.
Please also write a comment when one or more of your changes got merged.

**Comment by fzieris** [comment]
@tobous We need a permanent solution for this: Every Saros team member must be able to edit issues. No work-arounds, please.

**Comment by tobous** [comment]
@fzieris GitHub only allows users with write permission (and above) on the repository to edit issues and comments.
Currently, Saros developers only have read permissions (meaning they can read and clone the repository).
Write permissions would mean they could also directly push to the repository. If this is the wanted access right for the developers group, we should first correctly set up branch protection rules for any important branches, especially the master.

But this is not my decision to make. @m273d15

**Comment by m273d15** [comment]
Now everybody should be able to edit issues. I granted write permissions and configured the master branch as 'protected'. Please don't merge pull requests.

@tobous Are there other branches that require protection?

**Comment by tobous** [comment]
@m273d15 I would protect every branch that is long-living and is (or theoretically could be) used by multiple developers.

For the current branches, I would 
- set the Saros/I release branch `release/intellij-0.1.0` as protected
- set the two development branches `development/wbReinterate` and `development/actionAwareness` as protected if they are still relevant/valid
- not set the branches `gh_pages` and `build_via_gradle` as protected as they are your "own" development branches

**Comment by m273d15** [comment]
@jafey is the status of the commits, you mentioned in the list, still up-to-date?
