### ISSUE TITLE
Saros can't connect to XMPP server("saros-con.imp.fu-berlin.de")

### ISSUE THREAD

**Issue by RandomModderJDK** [saros-project/saros#1136]
**Describe the bug**
Saros shows Connection error, but i can go on saros-con.imp.fu-berlin.de in my browser.
The Detailed Error is:
SMACK: remote-server-error(502)
saros-con.imp.fu-berlin.de:5222 Exception: XMPPError connection to 
saros-con.imp.fu-berlin.de:5222;

**To Reproduce**
1. I click on connect or just start the IDE

**Expected behavior**
It just schould connect

**Log files**

https://pastebin.com/9vfL0QeY
https://workupload.com/file/KZWDUY6Lqvz
^^Had to upload on workupload, file is to big for pastebin and/or hastebin

**Screenshots**
![grafik](https://user-images.githubusercontent.com/62660085/111601677-e2a0c100-87d2-11eb-958a-b9b3962139aa.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - IDE Eclipse 2021-03 (4.19.0.v20210312-0638)
 - Saros Version 15.0.0

**Additional context**
I din't find the right file for the Saros log, the uploaded log is from 2020-09-07. But i think it's the same error, but i'm not sure

**Comment by tobous** [comment]
@Drakulix Seems like the XMPP server is down. Could you have a look at it?

**Comment by srossbach** [comment]
Yes the server is down. I am getting tired reading such "issue" as issues an the issue tracker. It is just annoying. Such things can happen. It is not worth ANY entry in the issue tracker.
