### ISSUE TITLE
None of the saros buttons work.

### ISSUE THREAD

**Issue by Aholicknight** [saros-project/saros#1148]
![8MlSOv0BKX](https://user-images.githubusercontent.com/7843719/134089154-e5acbb6c-6ebe-4c00-95d0-c380eee7d3d9.gif)

I am using eclipse  2021-06 (4.20.0) and it is not working. I uninstalled it and reinstalled it and that doe snot work as well.

**Comment by Aholicknight** [comment]
![image](https://user-images.githubusercontent.com/7843719/134089530-1315a8c5-fc40-48e8-aa37-f852efc8f9ca.png)
Opening the error log shows this

**Comment by GA-MV** [comment]
Hi. I'm also facing the same issue. I've tried uninstalling and reinstalling Saros, but the same thing happens -- still, none of the buttons work. 
I have the eclipse.buildId=4.21.0.I20210906-0500 and java.version=16.0.2

**Comment by gamma-02** [comment]
I'm getting the same issue.

**Comment by Aholicknight** [comment]
@gamma-02 Not related, but glad that you watch Lost. Hard to come by as people don't really know that show exists. Long Live DHARMA initiative.

**Comment by gamma-02** [comment]
Hah, yes!

**Comment by srossbach** [comment]
We have a template for reporting bugs. The screenshots/videos are not very helpful. If you do not provide the details (see bug report template) we cannot help you with your issue(s), THANK YOU!

**Comment by srossbach** [comment]
Seems to be a duplicate of  #1142
