### ISSUE TITLE
Saros seems to be broken on linux

### ISSUE THREAD

**Issue by lele92007** [saros-project/saros#1152]
**Describe the bug**
saros dosen't work at all in linux.
the buttons appear but won't do anything on click
when trying to open saros via the window button, saros throw an error `Plug-in saros.eclipse was unable to load class saros.ui.views.SarosView.`

**To Reproduce**
1. Install eclipse on linux
2. Install saros
3. Try to use saros, either via the "saros" menu or by opening a window for saros
4. the saros menu won't do anything, you will see the error in the window

**Expected behavior**
Saros should behave properly and should not send any error codes

**Log files**
https://gist.github.com/lele92007/1ec04424d72dba6938e83df73487267c

**Environment (please complete the following information):**
 - Pop-OS 21.10
 - EclipseIDE 21.09
 - 15.0.0

**Additional context**
I installed saros via the eclipse marketplace

**Comment by XintongMa** [comment]
Does it work on windows for you? It show me same error on windows

**Comment by bsutton** [comment]
I can confirm that it isn't working on linux.

ubuntu 21.10
eclipse 2021-Dec.

The menus do nothing.
I'm not seeing any errors even in the Error Log view.

**Comment by srossbach** [comment]
#1142
