### ISSUE TITLE
Discuss our stance on save action in IntelliJ

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#118]
As expressed in #117, automatic save action are currently problematic for annotation integrity in Saros/.

Independent of this problem, we have to think about whether we want to discourage the usage of save actions with Saros/I in general. (The final decision whether to use save actions is in the hand of the user anyway.)

With the predefined save action, which strips trailing spaces from a file, there is a safeguard enabled by default not to modify the caret line. This ensures that the save action does not impede the workflow of the user (for example by removing the automatically added indentation on a line the user currently wants to type on). This safeguard does not work for save actions triggered by other participants, meaning this save action could remove the indentation from a line another user just started typing on. Even though this is not a critical problem, it can lessen the usability of Saros as it impedes the normal workflow with IntelliJ.

IntelliJ by default saves the editor every time it is closed or "the frame is deactivated" (I would guess they mean when it loses the focus), meaning these save actions are applied a lot during a normal session. (There is also an option to save every modified editor when the application is idle for X seconds, 15 seconds by default.)

This problem gets worse with more elaborate save actions, as contradictory save rules could lead to a sort of edit war between the participants, creating countless unnecessary text edits.
Even though custom save actions are not a part of IntelliJ itself, they can be added trough the plugin [Save Actions](https://plugins.jetbrains.com/plugin/7642-save-actions).

This is not a pressing issue for now as I would suggest to set the deactivation of any save actions as a requirement of the alpha release, but an official decisions should be made before the official release of Saros/I.

**Comment by tobous** [comment]
@m273d15 You also mentioned something about custom save actions in IntelliJ. I am not sure if you meant the plugin or if there are other options I missed. The plugin "Save Actions" allows you to automatically apply the local code-style configuration, but I could not find other custom actions. (But I only skimmed the plugin page.)

**Comment by m273d15** [comment]
I also did not found custom save actions. Probably I mixed up intellij save actions with something else.

Is this also a problem in Saros/E?

**Comment by fzieris** [comment]
The stance is clear: Saros must not interfere with the developer's IDE/workflow. All existing features must work as they would without Saros around, and the developers need to have full control over their source code.

Both tickets (#117 and #118) are quite verbose, so don't really get the particular problem. Might be due to the texts filling multiple smartphone screens or my inattentiveness. I'll give it another try later.

**Comment by tobous** [comment]
The base problem of this ticket is that there are certain safeguards with the whitespace save action that do not apply to other participants. The save action does not change the caret line (with the default settings), but other participants might have other caret lines.

While skimming the IntelliJ CaretModel javadoc, I found something about multi caret editors, which might solve this problem. This would enable us to ensure that the caret lines of all participant's won't be changed by the save action. But this is only a very basic theory. I haven't looked into it any further.

**Comment by m273d15** [comment]
@tobous Is this discussion still open or can we close this issue?

**Comment by tobous** [comment]
All done. Can be closed.
