### ISSUE TITLE
How to handle stacked pull requests?

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#133]
### Assumption:
We have three feature changes F1,F2,F3 and F2 depends on F1 and F3 depends on F2.
This leads to a stack/chain of changes. The old gerrit system was able to handle such chains.

How do we handle these chains in GitHub?

### My first proposal was to:
* chain the branches corresponding to the dependencies of the changes
  * Create a branch `branch-f1` that bases on `master`
  * Create a branch `branch-f2` that bases on `branch-f1`
  * Create a branch `branch-f3` that bases on `branch-f2`
* Create corresponding pull requests
* Merge the pull requests in the order
  * Merge `branch-f1`
  * Change target of F2 (`branch-f2`) pull request to `master`
  * Rebase `branch-f2`
  * Merge `branch-f2`
  * Change target of F3 (`branch-f3`) pull request to `master`
  * Rebase `branch-f3`
  * Merge `branch-f3`

#### Advantages
* Each pull request contains the changes of the specific feature (dependent commits are not shown)

#### Disadvantages
* The rebase process removes existing approvals

See [here](https://graysonkoonce.com/stacked-pull-requests-keeping-github-diffs-small/) fore another approach that uses another merge order.

Are there other proposals how this process can be simplified?

**Comment by stefaus** [comment]
The other approach, has the disadvantage of waiting till every PR in line is approved (in the review time, new PRs could be created and this could take forever). 

This could reduce some work and maybe keep the reviews untouched, but have to try it out first: [Managing dependent pull requests](https://wchargin.github.io/posts/managing-dependent-pull-requests/)

**Comment by m273d15** [comment]
In order to simplify the reviewing process of stacked PRs it can be useful to use the GitHub filter function with the arguments `is:pr is:open base:master`.
