### ISSUE TITLE
ContactListItem in StartSessionWizard is not selectable

### ISSUE THREAD

**Issue by jafey** [saros-project/saros#152]
When you open the StartSessionWizard in the HTML-GUI
and click on "Next" to see the "Choose Contacts" step
then you cannot select a user by clicking on the item in the list.

To reproduce the issue, the [StartSessionWizardTest.java](https://github.com/saros-project/saros/blob/aa080e6c5406e551aac3b3b5bd98060d391d877d/de.fu_berlin.inf.dpp/test/stf/de/fu_berlin/inf/dpp/stf/test/html/StartSessionWizardTest.java) can be used.

In this screenshot you can see the problem, the user Bob is not selectable.
![image](https://user-images.githubusercontent.com/23552401/42949233-9731b04a-8b71-11e8-9bda-d79cbd6c33d4.png)

Strange Thing:
When you open the page in chrome and mock the contactList via SarosApi.trigger(), then you will be able to select the contact item

![image](https://user-images.githubusercontent.com/23552401/42949565-4e26cc18-8b72-11e8-8bc8-5e210389a144.png)

**Comment by m273d15** [comment]
Closed the issue, because we stopped working on the HTML GUI approach #682
