### ISSUE TITLE
Saros/E automatically connects to a pre-existing account when adding new accounts

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#153]
When offline and adding a new XMPP account to Saros while there are already accounts registered, when finishing the wizard, Saros automatically connects to a pre-existing account (probably the default account).

This behavior seems confusing. 

### Steps to reproduce
1. Start Saros
1.1 Add a new account to Saros (optional, if there is already an existing account)
2. Go offline
3. Add new account to Saros through the wizard
4. Finish the wizard

This connects to the current default XMPP account, which is unexpected behavior.

Expected behavior:
* Some form of acknowledgement, that adding the new account was successful
* Optional: Automatically connect to XMPP server using the newly entered account

**Comment by srossbach** [comment]
The problem is that https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/ui/wizards/ConfigurationWizard.java inherit from https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp/src/de/fu_berlin/inf/dpp/ui/wizards/AddXMPPAccountWizard.java

Should not be hard to fix.

**Comment by m273d15** [comment]
See #153 for further discussions

**Comment by srossbach** [comment]
![image](https://user-images.githubusercontent.com/41400679/62149552-445da000-b2fc-11e9-9e75-1da60db70b65.png)

When you use this option to create XMPP accounts I guess it is much more clear what is actually happening. My big guess is that you uses the context menu in the connect button ?

**Comment by srossbach** [comment]
@tobous can you please change the description ?

After I am done with the "rework" you can expect:

You are automatically connected if you create an account (ON THE SERVER !) and checked Use Now button

TBD if this account should also be the default one

-------------------------------------------------------

If you finished the ConfigurationWizard

The account is set as the default one regardless if there was already a default account
A connection attempt is made only if auto-connect on startup is selected

------------------------------------------

Adding / Removing / Editing / Set as Default|Activating    an account

Does not perform a connection. Does not set the account as the default one (unless the store is empty - this is done by the store itself)

**Comment by tobous** [comment]
I am not sure what you mean/what I am supposed to put into the description. But, with your permissions, you should be able to edit the description yourself.

Also, if there are already existing PRs for the rework that address some of these points, please also link them to this issue.

**Comment by srossbach** [comment]
So if your issue is only that the auto-connect is triggered after you entered an account then this was fixed with #606 

See https://github.com/saros-project/saros/commit/b524b5052a84be540d99db28a737e56c54255e23#diff-ebde9d1128cf491db859c1efec978a63R42

However looking at the "expected behavior". This sounds more like a feature or feature change than actually being a bug.

**Comment by tobous** [comment]
The issue was two-fold. Firstly, Saros automatically connected to an account when adding a new onem and secondly, Saros automatically connected to a *different* account than the created one.

If the first issue is solved, as you stated, than that should subsequently also resolve the second issue.

The request for user feedback came from @fzieris, who discovered the issue while we were testing something in Saros/E. And yes, I can see that this makes it more of a feature request than a "bug". I am fine with just not connecting to the account automatically.

**Comment by srossbach** [comment]
I guess I will have to rename the Preference to AutoConnectOnStartup to make clear what the intention of this preference is.

And then I think we have to add some small buttons into several account pages with: Set as Default and Connect Now

I still have issues that the Eclipse Connect actions sets every account you select to connect with as default but that is another story that has to be decided.
