### ISSUE TITLE
Initial Host-Only Execution of ProjectTypeNegotiationHook Fails

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#168]
All negotiation hooks are initially called on the host side before a client is present. See https://github.com/saros-project/saros/blob/92b2e4c8a83c38c2fa689480b85376ef9280c88b/de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/session/SarosSessionManager.java#L247
This call fails for the ProjectTypeNegotiationHook, as `tellHostPreferences()` sets the preference with the key `KEY_PREFERRED_TYPE`, but `applyActualPreferences(...)` uses the key `KEY_TYPE` when looking for the preferences. This causes `applyActualPreferences(...)` to always return with a warning for this initial call.

This problem stems from the ColorNegotiationHook, which needs this initial call before a client is connected. This looks like a general problem with the new hook design, as it was added as a general solution that most likely is not needed for most hooks.

### Steps to Reproduce

1. Start a session with another participant

### Possible Solution Approaches

I can think of three possible solution approaches:
- Add a new convention to deal with this: Require hooks that don't need this initial setting of preferences to return without a warning if `null` is passed for the client preference object. (This approach is currently used in ModuleTypeNegotiationHook.)
- Introduce a new method that returns a boolean whether this initial call to set the host preferences should be run. Check this boolean for the call in SarosSessionManager.
- Introduce a new method that is only used for this initial call to set the host preferences. This method is used in SarosSessionManager. If a hook does not need to set any initial preferences, this hook is left as a NOP.

**Comment by stefaus** [comment]
Without thinking to much about a optimal solution, As a quick and easy solution I would be fine with to just use one `KEY_TYPE`, with a value like `projectNegotiationTypePreferred`. On the pro side, its easy to implement, just works and less error prone, on the other the name is arguable.

Or something like
```java
if (input == null || !input.containsKey(KEY_PREFERRED_TYPE)) {
    if (input == null || !input.containsKey(KEY_TYPE)) {
        String inputType = input.get(KEY_TYPE)
...
```
To handle this in general:
Approach 1 needs the future dev to read the doc, but also easy to fix for now
number 2 is not my favorite,
3 could be like `applyInitialParameters(hostProperties)`

From my point of view, just works would be enough.

**Comment by tobous** [comment]
I would prefer a general solution. Otherwise, we force a somewhat unnecessary restriction (`tellHostPreferences()` and `considerClientPreferences(...)` both need to return preferences compatible with `applyActualParameters(...)`) which is unnecessary in a lot of cases. Furthermore, this seems error-prone to me (as we have seen with this issue).

I would prefer option 3. I would suggest to replace `tellHostPreferences` with such a new method, as it was just added to enable the initial setting of the preferences for the ColorNegotiationHook. The method should then no longer be used inside the hook, which is not really useful anyway as we already have access to everything `tellHostPreferences` has access to.
Should then be reworked in https://github.com/saros-project/saros/blob/92b2e4c8a83c38c2fa689480b85376ef9280c88b/de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/session/ProjectNegotiationTypeHook.java#L73

**Comment by stefaus** [comment]
Good, in this TypeHook  `tellHostPreferences()` can easy be to changed to `getLocalPreference()`.

**Comment by tobous** [comment]
Fixed by https://github.com/saros-project/saros/commit/09f5550ada821af3072160f114b16c7cccf24b2e.
