### ISSUE TITLE
Inconsistent dialog for project selection upon invitation

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#20]
The dialog for selecting the target project as a participant upon a session invitation is a complete mess.

- The title "add projects" is just wrong.
- The subtitle "Select local project." does not give a reason, why i need to do that
- the header of the tab control is useless
- the tab control itself is pointless \(always only 1 tab...\)
- The hint in the header is weird "Please set a project name to update from" &gt; i don't update "from" a "project name"... i select a project where saros is supposed to put the files from the inviting host to...
- "Create copy for working distributed" is easily misinterpreted/wrongly named \(see other bug\).

- "Explain" button for disabling version control support -&gt; this should be a standards/guideline compliant inline help trigger.
There should also be explanations for "scan workspace" &gt;  doesnt work for partial sharing \(maybe it should?\) so at least that needs to be documented

\[As part of my diploma thesis this will be refactored too\]

Reported by: netcorps

Original Ticket: [dpp/bugs/644](https://sourceforge.net/p/dpp/bugs/644)

**Comment by srossbach** [comment]
Outdated.
