### ISSUE TITLE
Saros sometimes creates ChecksumActivities for deleted/moved files

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#233]
The [`ConsistencyWatchdogServer`](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/concurrent/watchdog/ConsistencyWatchdogServer.java) running on the host periodically creates ChecksumActivities and broadcasts them to all other session participants. The host determines which files to send these activities for by checking which files are open in a local or remote editor (see [lines 214-219](https://github.com/saros-project/saros/blob/88bcb01524978c5c5e01f60b7d0ae658951dc18a/de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/concurrent/watchdog/ConsistencyWatchdogServer.java#L214).

This is problematic when such ChecksumActivities are triggered after a file was deleted/moved by the host but before these send activities for the deletion/move were executed by the clients and at least one of the clients has an open editor for the deleted/moved file. In such a case, the host still sends a ChecksumActivity for the deleted file/the old path of the moved file, as there are still remote editors for the file. Once all clients executed the send deletion/move activities and subsequently closed the editors with the old file path, the host will no longer generate ChecksumActivities for these files.

As activities are executed in the correct order, these faulty Checksum activities are executed after the deletion/move activities, meaning the clients no longer have a matching file for the ChecksumActivitiy. This leads to an inconsistency where the clients think they are missing a file that is present on the host's side. This inconsistency can not be resolved through the recovery as the host fails when trying to read the content of the "missing" file requested by the clients (as the file no longer exists).

This bug triggers consistently for Saros/I but does not seem to trigger with the current setup of Saros/E. It is hard to reproduce for Saros/E as it is dependent on the timing of checksum activities. With my setup, I was able to somewhat consistently trigger it on Saros/E by reducing the `CHECKSUM_CALCULATION_INTERVAL` to 200 (from it's original value of 10000).

#### Steps to Reproduce
Needed setup: Reduce the `CHECKSUM_CALCULATION_INTERVAL` in the [`ConsistencyWatchdogServer`](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/concurrent/watchdog/ConsistencyWatchdogServer.java) to 200.

1. Alice and Bob start a session with a file A
2. Bob opens file A
3. Alice deletes/moves the file A

This causes Bob do detect an inconsistency that can not be resolved through the recovery.

#### Possible Solution Approaches

To resolve this issue, I would suggest to differentiate between remote and local editors when sending ChecksumActivities. When sending ChecksumActivities for files only open in remote editors, we should first check whether the file exists locally. If it does not exist, we should not send a ChecksumActivity but instead directly handle it as a superfluous file on the client side.

To reduce the rate of false-positives, we should also give the clients some time to reach a consistent state  before acting.
This can be done by introducing a set waiting period (for example 5 cycles/triggers) in which the host does not send ChecksumActivities for deleted/moved files. This should hopefully give the clients enough time to close the editors for the deleted/moved files.
Such a waiting period could be introduced by holding a list of the removed/moved files together with a counter for each of them. Every time a ChecksumActivity for such files would be triggered, the counter is reduced by one. If the counter reaches zero, the file is removed from the list and ChecksumActivities are send as normal.
Such a waiting period/timeout based approach has the drawback that it can still lead to problems if the clients take to long to process the deletion/move activities. On the other hand, it should reduce the number of false-positive inconsistency detections while still enabling us to notice when a file deletion/move activity was dropped.

EDIT: The second suggestion to introduce the buffer only works for files deleted by the host. The client could filter incoming ChecksumActivities, but it can not determine when a cycle of ChecksumActivity dispatches is done, meaning it is hard to determine how long the client is supposed to drop such activities for a certain file.

**Comment by srossbach** [comment]
Multiple things got broken when the logic changed in the WatchDog client and server part. Originally it operated on files. However it now operates on the document itself and not its file. So it is now possible to have an editor open that do not have file representation.

As long as you do not close the editor on the host side I do not know what will happen.

**Comment by tobous** [comment]
@srossbach I don't understand your last statement. Could you elaborate? Do you mean the actual editor on the host side or the reference to the remote editor for the file held by the host?

**Comment by srossbach** [comment]
I have no tested it yet. As it seems when we are calling getEditorContent we use a FileEditorInput object. However I am not sure what Eclipse does if a provider is still connected to this editor.

In general:

Calling provider.connect will add a counter to a document. Unless this counter is zero it will be hold in memory. So if a client opens an editor it will "open" as well on the host side (without even being visible) and all edits are applied to such an editor.

I am still wondering why the host do not send a correct checksum (indicating that this document/file) no longer exists even if some former checksum activities where either not correct or got wrongly applied.

It should not matter and the recovery should be successful after a few attempts.

**Comment by tobous** [comment]
Fixed by #246.
