### ISSUE TITLE
Remove unhelpful annotation "eclipse in background"

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#25]
The icon annotation \(the clock......\) for users which have their eclipse window in the background should be removed.

It does not help users because they cannot understand what that thing means \(clock? time? busy?\), unless it was explained to them. After understanding what it means it was never used.

It complicates the UI of saros and does not help, so: away with it\!

If anyone is against the removal, i can provide a detailed explanation of why it is not necessary and should be removed to simplify the saros ui if it's not clear yet.

Reported by: netcorps

Original Ticket: [dpp/bugs/696](https://sourceforge.net/p/dpp/bugs/696)

**Comment by srossbach** [comment]
Feature got removed long, long, very long time ago.
