### ISSUE TITLE
Creating files in shared directory during partial sharing does not work correctly

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#256]
Saros/E does not correctly handle file creations during a partial session. This leads to two separate wrong behaviors. These issues were also shortly discussed in #235.

### Creating a file in a shared folder that contains any non-shared resources
When creating a file in a shared folder that contains any non-shared resources, the file creation will not be propagated to other participants. The clients log the following error:
```
ERROR 14:59:34,605 [main] (SarosSession.java:828) PSFIC - unable to update partial sharing state, parent is not shared for file: L/Project/src/A/Created.java (EclipseFileImpl)
```
When continuing the session, the session is also logged by the host later on. But this might be an unrelated issue or a consequence of the initial misbehavior.
```
TRACE 15:06:58,247 [ModalContext] (SharedResourcesManager.java:223) received resource change event caused by job  ='Implicit Job'
TRACE 15:06:58,247 [ModalContext] (SharedResourcesManager.java:234) received resource delta 'ResourceDelta(/)' contains:
C(0) /
C(0) /Project
C(0) /Project/src
C(0) /Project/src/A
A /Project/src/A/Created.java

TRACE 15:06:58,248 [ModalContext] (SharedResourcesManager.java:282) generated resource activities for current resource delta 'ResourceDelta(/)' : [FileActivity [dst:path=SPath [project=P/Project (EclipseProjectImpl), projectRelativePath=src/A/Created.java], src:path=N/A, type=CREATED, encoding=N/A, content=38 byte(s)]]
ERROR 15:06:58,266 [main] (SarosSession.java:828) PSFIC - unable to update partial sharing state, parent is not shared for file: L/Project/src/A/Created.java (EclipseFileImpl)
TRACE 15:06:58,382 [main] (EditorManager.java:814) .partOpened invoked
TRACE 15:06:58,385 [Worker-9] (FileSystemChecksumCache.java:92) invalidating checksum for existing file: /Project/bin/A/Created.class [0x930F1D161C4EE038F906555DE31FF]
TRACE 15:06:58,386 [Worker-9] (SharedResourcesManager.java:223) received resource change event caused by job  ='Building workspace'
TRACE 15:06:58,386 [Worker-9] (SharedResourcesManager.java:234) received resource delta 'ResourceDelta(/)' contains:
C(0) /
C(0) /Project
C(0) * /Project/bin
C(0) * /Project/bin/A
A * /Project/bin/A/Created.class

TRACE 15:06:58,386 [Worker-9] (SharedResourcesManager.java:282) generated resource activities for current resource delta 'ResourceDelta(/)' : []
```

#### Steps to Reproduce
Alice and Bob both have the same initial content for the shared project:
```
Project
 |-> src
      |-> A (shared)
          |-> B (shared)
          |   |-> Shared_file (shared)
          |
          |-> C (not shared)
              |-> Non_shared_file (not shared)
```
1. Alice and Bob start a partial session on the given project configuration, sharing the resoruces A, B, and Shared_file and explicitly not sharing the resources C and Non_shared_file.
2. Alice creates a file in the directory A

### Creating a file in a shared folder that does not contain any non-shared resources
When creating a file in a shared folder that does not contain any non-shared resources, the file creation will be properly propagated to the other session participants and subsequent activities by the file creator will be correctly transferred. But actions for the file created by other participants will be not be transferred, thereby triggering an inconsistency. The client logs the following error:
```
ERROR 15:07:22,937 [main] (SarosSession.java:828) PSFIC - unable to update partial sharing state, parent is not shared for file: L/Project/src/A/B/Testing.java (EclipseFileImpl)
```

#### Steps to Reproduce
Alice and Bob both have the same initial content for the shared project:
```
Project
 |-> src
      |-> A (shared)
          |-> B (shared)
          |   |-> Shared_file (shared)
          |
          |-> C (not shared)
              |-> Non_shared_file (not shared)
```
1. Alice and Bob start a partial session on the given project configuration, sharing the resoruces A, B, and Shared_file and explicitly not sharing the resources C and Non_shared_file.
2. Alice creates a file in the directory B.

**Comment by srossbach** [comment]
Just for clarification to anyone who is interested or working on this issue.

I added such checks to prevent overwriting of non shared files. As a result this behavior is unwanted but better than just deleting someones files. There are also additional checks in the IPN logic that prevent file deletion.

After the new ReferencePointLogic is added we can (as this will remove full sharing, better we have to) start a discussion what should get deleted during synchronization and what not and what is allowed on file activities. As the current usage of partial sharing is very small (at least from former data) this behavior does not affect many users and in my opinion is still better than some unnoticed file deletion.
