### ISSUE TITLE
Too much jar-libs checked in

### ISSUE THREAD

**Issue by donut87** [saros-project/saros#267]
Currently, there are 81 jars checked in into the git. This number is should be reduced by 81. Thinking about 'the repo footprint' it might be a good idea to get rid of this and provide a dependency management tool for new libraries.

**Comment by tobous** [comment]
Building saros (and managing dependencies) using gradle is currently being worked on by @m273d15. See PR #236 & #239. This will eliminate the need for most jars in the repo (excluding some modified jars).
