### ISSUE TITLE
Adding the Git Support into the Invitation Process

### ISSUE THREAD

**Issue by chrismotian** [saros-project/saros#301]
We need to decide where the user can _click_ on _Support Git_ and how to implement this option. I would prefer to add this at the begin of the Invitation because the shared files are also chosen at the begin of the code and if the user wants to support Git we should have constraints about which files are possible to choose. The first constraint is **share the whole git working directory** because we want to have both sides on the same commit. I would decide that checking the constraint will take place on the host side on the `StartSessionWizard` and `ResourceSelectionWizardPage` because both handle the selected resources before the session started. I would appreciate any kind of opinion about my decision.

**Comment by srossbach** [comment]
The StartSessionWizard is hardly used. Most people will just use the context menu to share projects. The handler skips the wizard and calls the CollaborationUtil instead.

**Comment by m273d15** [comment]
In my opinion thinking about this aspect is to early. You should implement just a basic prototype that allows to share commits. The next step would be to verify whether this commit can be applied, error handling and so on...
