### ISSUE TITLE
Send a commit via Saros

### ISSUE THREAD

**Issue by chrismotian** [saros-project/saros#324]
I want to write a Scenario to clarify the design and requirements. Questions or suggestions are welcome.
This will be the most important feature of the Git support for Saros.

Scenario: Sending a commit via Saros
System under discussion: IDE with Saros Plugin
Primary Actor: Alice 
Secondary Actor: Bob 
Goal: Alice and Bob are on the same branch and commit
Conditions: Both users in Saros session, Both users on the same branch, Each user have their own .git directory, Alice has one commit more than Bob

Steps: 
1. Alice click on "Share Commit with Bob"
2. IDE check if Bob meet the requirements to apply the commit
3. IDE sends the commit via Saros. The commit is zipped as a [bundle-file](https://git-scm.com/docs/git-bundle)
4. IDE unbundle the file to Bob's repository.

**Comment by chrismotian** [comment]
Hey @stefaus ,
I am eliciting the best way to share the bundle-file during a saros session. Kelvin gives me the hint that you have analyzed time to send files with the given protocols in Saros and to ask for your expertise. 
Long story short, I want to send packs of commits during a session. Because of that, the expected file size will be small (some KB), but can grow in the worst case to the size of the whole .git directory.

**Comment by stefaus** [comment]
Hey @chrismotian,
some kB would be Ok for Activity based transmission, but in terms of transmission speed the best approach is to use XMPP File Transfers (like the Project Negotiation does).
Currently the File Transfer classes of the XMPP Library are used directly and to add new handlers this should be changed first. I created #347 for this topic.

**Comment by chrismotian** [comment]
Because the most common use case expect that the user already have parts of the Repository the bundle-file size will be small (< 1 kB). This is because we just need to send the diff. **I decide to use activities.**
