### ISSUE TITLE
Replace abstract null implementations of interfaces with interface defaults

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#342]
As an artifact of using an older java version, there are still multiple abstract null classes whose sole purpose it is to implement every method in the interface with a NOP. For an example, see [NullSessionLifecycleListener](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.core/src/de/fu_berlin/inf/dpp/session/NullSessionLifecycleListener.java).

Such classes should be removed and default implementations should be added to the interface instead. Most likely, all of these default implementations will be NOPs as well.

**Comment by srossbach** [comment]
Eclipse and Core part should be finished with #344 and #345 . Anything missing in IntelliJ ?

**Comment by tobous** [comment]
I don't think so. I think this ticket is completed.
