### ISSUE TITLE
Direct connections are only established if needed

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#35]
Inviter / Invitee connection is always established, thats all.

Connections to other session participants are only established if needed \(depends on the size of the packets to be transmitted\).

As long as there is no need for such a connection, the XMPP server is used by sending chat messages  \(which has no stream guarantees\).

Reported by: kargor

Original Ticket: [dpp/bugs/760](https://sourceforge.net/p/dpp/bugs/760)

**Comment by m273d15** [comment]
Removed the whiteboard component #831
