### ISSUE TITLE
Ignore the .git directory during a Saros session

### ISSUE THREAD

**Issue by chrismotian** [saros-project/saros#370]
As mentioned in the Saros FAQ we only provide safe usage of Saros and Git together when the git folder is on the same level as the eclipse project : [I'm working with a version control system, can I use Saros?](http://www.saros-project.org/faq) To change this limitation Saros should ignore files related to version control, what practical means not allowing to share .git directories at all. This can be done by marking the .git directory as derived. I need help with finding the right place for the implementation because I am not very familiar with file selection in Saros.

**Comment by tobous** [comment]
A file being marked as "derived" is an IDE concept coming from Eclipse (the IntelliJ equivalen is a file being marked as "excluded"). As such, there is currently no option to set this flag through Saros as far as I know (with good reason in my opinion). 
Marking the .git folder as derived/excluded is most likely the simplest solution. But I would still prefer a solution that does not require modifying the IDE/Project setup of the user as this might confuse them or cause problems with their setup.

Another solution would be to introduce a blacklist (just like the .gitignore file for git) that contains paths that should be ignored by Saros. This solution would be more complicated and would cause additional overhead but would allow us not to be dependent on modifying the project setup. (I think the biggest problem with this solution is finding a good place to put the check.)

If we were to use the derived/excluded flag for this functionality, I would still prefer not marking the directory automatically. A better compromise would be just offering the user the option to mark it as such, e.g. through a dialog box that is displayed when Saros is started. (To not annoy the user, it would also be better if they were only asked once for each project with a non-derived/excluded .git directory, but that is more of an implementation detail).

**Comment by chrismotian** [comment]
I agree with you on both. "the biggest problem with this solution is finding a good place to put the check" and "I would still prefer a solution that does not require modifying the IDE/Project setup of the user".
I was thinking about ignoring the .git directory from Saros, instead of setting in to "derived"/"excluded". This would cause fewer side-effects and less confusion. Additional we don't need to inform the user with this approach because sharing the git directory via Saros is always a bad idea. The Blacklist seems to contradict YAGNI because the git directory is the only target I want to ignore. 
Never than less, the "biggest problem" is"finding a good place to put the check"(check if the selected resource for sharing is the git directory and ignoring if true) and I appreciate any expertise.
