### ISSUE TITLE
Amount of activities

### ISSUE THREAD

**Issue by chrismotian** [saros-project/saros#388]
Regarding #372 and #324  I am wondering if there is a common sense about how many activities should be created to negotiate between users. Personally, I would argue that having one activity reduce complexity because we have all the logic in one place. Is there an argument for creating different flavored activities instead of a single activity? 
My use-case: 
-Alice: sends an activity to Bob 
-Bob: collect the HEAD-hash, sends an activity to Alice 
-Alice: create the file with the commits (from HEAD of Bob to HEAD of Alice), sends an activity to Bob
-Bob: fetching

**Comment by m273d15** [comment]
We are reactivating our [gitter channel](https://gitter.im/saros-project/saros). If you want to discuss an approach or an idea or ask a general question (as here), you should use gitter :wink: . Nonetheless, technical discussions about an issue should be located in the corresponding GitHub issue.
