### ISSUE TITLE
EditorManager may fire duplicate partActivated events

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#392]
When the follower closes the active editor, they correctly leave the follow mode. But the follow mode button does not seem to be updated correctly. If the button is clicked, the editor currently focused by the followee is also focused by the follower and the followee displays locally that the follow mode has started. But the follower does not scroll or switch editors when the followee does, meaning they are not in the follow mode. If the follower presses the follow mode button again in this state, nothing happens. The follow mode display for the followee is also not updated when the follower takes an action that would otherwise end the follow mode (like manually switching the editor).

This issue can be avoided by explicitly selecting "Follow user XYZ" from the drop down menu of the follow mode button instead of just clicking the follow mode button itself on the followee side to start the follow mode.

This issue does not always occur. Sometimes the button does seem to work in this situation. From my testing however, it seems that more often then not, the issue occurs.

This issue was found and first discussed as part of #390.
The logic behind the button is located in [FollowModeAction](https://github.com/saros-project/saros/blob/master/eclipse/src/saros/ui/actions/FollowModeAction.java), but the actual problem might be located elsewhere.

#### Steps to Reproduce
1. Alice and Bob start a session containing the shared files A and B.
2. Alice and Bob both open an editor for A and B.
3. Alice selects the file A.
4. Bob follows Alice.
  Bob now also has the file A selected.
5. Bob closes the editor for A.
  Bob has now left the follow mode. This is also correctly displayed by Alice.
6. Bob uses the follow mode button (not the drop-down menu, the button itself) to again start the follow mode.
  This causes Bob to re-open the editor selected by Alice. Alice now sees Bob as following here.
7. Alice scrolls the editor or changes the selected editor.
  This action will not be transmitted to Bob.

**Comment by srossbach** [comment]
After analyzing this someone this has nothing to do with the action. It is simply broken.

When you start follow mode you call EditorManager#jumpToUser which will trigger a listener forcing the follow mode to terminate.

So when you call FollowManager#follow you will generate a StopFollowingActitivty followed by a StartFollowingActivity. When the method returns you broadcasted a follow mode state however the internal state is non following.

**Comment by srossbach** [comment]
As it turns out we hook into partBroughtOnTop events. What is going on is something like:

EditorManager#jumpToUser

For what reason ever when opening / switching to the new editor a partBroughtOnTop event may be fired containing the current focused editor. The logic transforms this into an editorActivated event which gets passed back to the FollowModeManager before the FollowModeManager#follow method is even finished. The result is that the FollowModeManager state is changed to not following and after that it will report that it has start following.

**Comment by tobous** [comment]
Fixed by #640.
