### ISSUE TITLE
Travis builds fail while building HTML whiteboard

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#418]
Currently, all travis builds seem to fail because of the HTML whiteboard.

As the build of the master after merging the last PR worked and both the current master and the state before the fix fail, this seems to be caused by an external issue.

[Build on the current master (with NOP commit)](https://travis-ci.com/saros-project/saros/jobs/174967481)
[Build before the null check addition](https://travis-ci.com/saros-project/saros/jobs/174968529)

**Comment by m273d15** [comment]
The reason seem to be "terser" library. Therefore it has to be a transitive dependency. It seems as if there is a [solution](https://github.com/vuejs/vue-cli/issues/3407#issuecomment-459985313). I will check whether this solution works also for transitive dependencies.

**Comment by AbdBarho** [comment]
They are already working on a [solution](https://github.com/terser-js/terser/pull/254)
Hopefully by the end of the day it should be there.

The problem happens in the "inline-source-cli" plug-in, which bundles the JavaScript, CSS, and HTML into one file. It has a peer dependency to [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin/issues/66) which breaks with newer version of Treser (3.16.0)

There are alternatives to this plug-in in case the fix takes too long.

**Comment by m273d15** [comment]
#420 introduced a workaround. This workaround should be reverted as soon as the fix of the underlying issue (see in the previous comments) is integrated.
