### ISSUE TITLE
Allow compatibility with other Jetbrains Plugins

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#443]
Currently, the Saros/I plugin is only compatible with IntelliJ.
This is the case as the plugin does not declare any module dependencies, which makes it a "legacy plugin". See [compatibility documentation](http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html).

Before this is enabled on the master, the compatibility should be tested with some of the other Jetbrains IDEs.

**Comment by mpfau** [comment]
We successfully tested with Webstorm. It works as expected so far. Would be nice if it would be enabled and we would not have to create our own builds.

**Comment by ylieder** [comment]
> We successfully tested with Webstorm. It works as expected so far. Would be nice if it would be enabled and we would not have to create our own builds.

Could you provide short instructions on how to build the plugin from source and modify the set of compatible IDEs?
We would like to test it on PyCharm as well.

**Comment by mpfau** [comment]
Just uncomment line https://github.com/saros-project/saros/blob/master/intellij/resources/META-INF/plugin.xml#L42
and run gradle buildPlugin



15. Mai 2020, 15:24 von notifications@github.com:

**Comment by m273d15** [comment]
> Could you provide short instructions on how to build the plugin from source and modify the set of compatible IDEs?
We would like to test it on PyCharm as well.

Our nightly [builds](https://github.com/saros-project/saros/actions/runs/105596436) are also installable in all IDEs.
