### ISSUE TITLE
Whiteboard DH: Colour mechanics broken

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#45]
Note
====

As the subject of his master's thesis, a student introduced several substantial enhancements to the Whiteboard. The Swamp Tramps split up the resulting patch and put all on a branch in Gerrit. For the sake of brevity, I'll call this enhanced and newly reintegrated Whiteboard "Whiteboard DH". You will see this name in some other places in the issue tracker, too.

Problem Description
===================

In Whiteboard DH, one cannot create objects with a colour other than black (if that's a colour). And the fill button doesn't cause objects to be drawn filled, either.

To reproduce
============

1. Choose a colour other than black.
2. Draw a rectangle. As long as you don't release the mouse button, the rectangle has the chosen colour. As soon as you release the button, the rectangle turns black.
3. Activate the fill button (inkpot).
4. Draw another rectangle. It isn't filled.

Insights
========

In the old Whiteboard colours worked like this: In a colour chooser you set foreground and background colour and new objects looked these colours up on creation. Now new objects are passed the colour in their constructors, but something goes wrong before or after this. An interesting point is that <code>LayoutElementRecord.getColor()</code> never enters the <code>if</code>-Block.

Reported by: rmoehn

Original Ticket: [dpp/bugs/810](https://sourceforge.net/p/dpp/bugs/810)

**Comment by AbdBarho** [comment]
the work of Hendrik Degner never got fully integrated in the whiteboard, consequently, all features regarding color are not available neither in the old nor the html whiteboard.
