### ISSUE TITLE
Strange behaviour of Connection configurations in ConfigurationSettingsWizardPage

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#456]
1. It is not possible to uncheck the "Shall your contacts see your Skype username?" checkbox if no content is in the text box beside the checkbox. (see gif below)
2. If you change the state of the "Automatically connect to XMPP server on Eclipse startup?" you always uncheck the "Shall your contacts see your Skype username?" checkbox. (see gif below)

![strange_behaviour_1](https://user-images.githubusercontent.com/7346610/53399492-64cfaa00-39ac-11e9-8a0c-280e90f89043.gif)

**Comment by srossbach** [comment]
I think removing the FocusListener @ https://github.com/saros-project/saros/blob/master/eclipse/src/saros/ui/wizards/pages/ConfigurationSettingsWizardPage.java#L276

should do the trick.
