### ISSUE TITLE
Whiteboard DH: No copy and paste for arrows and lines

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#46]
Problem description
===================

In Whiteboard DH all objects can be copied and pasted, only arrows and lines can't.

To reproduce
============

1. Draw a straight line (not with freehand tool).
2. Select it.
3. Hit Ctrl-C. The clipboard button lights up.
4. Hit Ctrl-V. Nothing happens.
5. Click the clipboard button. Nothing happens.

Copying with the copy button doesn't work, either.

Reported by: rmoehn

Original Ticket: [dpp/bugs/811](https://sourceforge.net/p/dpp/bugs/811)

**Comment by AbdBarho** [comment]
the work of Hendrik Degner never got fully integrated in the whiteboard, consequently, arrows are not available neither in the old nor in the html whiteboard.
