### ISSUE TITLE
The "Work Together On.." dropdown list contains only the first project

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#469]
The dropdown list of the "Work Together On.." context menu in the saros view contains only the first project instead of all available projects.

E.g. If the project tree contains three projects `A-project`, `B-project`, `C-project` only the project `A-project` is contained in the dropdown list.

**Comment by srossbach** [comment]
https://stackoverflow.com/questions/12315749/e4-dynamic-menu-contributions

**Comment by srossbach** [comment]
https://github.com/saros-project/saros/blob/master/eclipse/src/saros/ui/menuContributions/StartSessionWithProjects.java is the affected class. I checked the class and the logic is working. So I guess it is an Eclipse issue that does not properly show the context menu entries.

**Comment by m273d15** [comment]
It seems as if #473 is required before using dynamic context menus in the eclipse 4 environment. For now I would remove the dynamic list and replace the "Work Together On.." entry with a "Share Project(s).." entry that opens the dialog for sharing projects.

**Comment by m273d15** [comment]
Implemented a workaround in #521. After migrating to e4 we should re-implemented these dynamic menus!
