### ISSUE TITLE
Whiteboard DH: Strange behaviour of line and arrow drawing tool

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#47]
Problem description
===================

If you click in a special way (!), the line or arrow drawing tool prompts you for drawing another line segment or arrow right at the end of the first one (and so on). It behaves like the line drawing tool of other vector drawing programs (Inkscape, for example), but neither consistently nor beautifully so.

To reproduce
============

As it is not consistent, it is not consistently reproducible. However, try drawing a line (a dragging action) and keep the mouse moving when you release the button. With arrows you might also get arrowheads in strange places.

Another way to produce strange behaviour is just clicking on the canvas while moving the mouse.

Insights
========

The hack in <code>DragConnectionCreationTool</code> might be causing this.

Reported by: rmoehn

Original Ticket: [dpp/bugs/812](https://sourceforge.net/p/dpp/bugs/812)

**Comment by AbdBarho** [comment]
the work of Hendrik Degner never got fully integrated in the whiteboard, consequently, arrows are not available neither in the old nor in the html whiteboard.
