### ISSUE TITLE
Mark 'bin' directory as excluded for IntelliJ IDEA

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#490]
In each project directory (except 'ui.frontend'), there are two folders containing binary artifacts: `bin` and `build`.

Currently, only the `build` folder is marked as excluded by default in IntelliJ. This leads to build artifacts (like .class files) being found by the IntelliJ search, adding unnecessary bloat to the search results.

Either the `bin` directory should be configured to also be marked as 'excluded' by default through the gradle config or the two build directories should be combined.

**Comment by tobous** [comment]
Just out of curiosity: Why do we have two directories for build artifacts anyways?

**Comment by m273d15** [comment]
This is a based on the fact that the eclipse infrastructure just consumes the dependencies of gradles and uses its own build tool (PDE) which uses the bin dir. I am still thinking about improvements of the eclipse + gradle workflow.
