### ISSUE TITLE
Rework serialization of ColorIDSet and XMPPAccount

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#491]
In order to persist the configured `XMPPAccount` and the `ColorIDSet` we have currently the following implementation:
* The `ColorIDSetStorage` class uses the default java serialization in the method `save` to serialize a list of `ColorIDSet`s and save the result in the preference store. 
* The `XMPPAccountStore` class uses the default java serialization in the method `saveAccounts` to serialize the current `activeAccount` and the configured `accounts`. The result of the serialization is encrypted and written to a file.

The disadvantage of this approach is that the saved data are highly coupled with the corresponding class implementation. Therefore changing the class name or package name would lead to invalidated data. Furthermore saros just throws an exception if the saved data cannot be deserialized.

**Comment by m273d15** [comment]
We already use XStream. We could use this library in order to avoid the rename issues with using [class aliasing](https://x-stream.github.io/alias-tutorial.html#class_aliasing) (and if required also [field aliasing](https://x-stream.github.io/alias-tutorial.html#field_aliasing))

**Comment by srossbach** [comment]
I have already a patch for the XMPP Account stuff. It is not that hard to serialize data by hand. There is no need to use XStream to generate "enterprise" XML files.

**Comment by m273d15** [comment]
@srossbach Oh sorry. I saw this post directly after pushing #492. If you want to push your solution I will close my PR.
