### ISSUE TITLE
Link to 'Naming Conventions' in best-practices documentation does not work

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#495]
The link on the best-practices page in the section 'Classes and Interfaces' pointing to the page 'Naming Conventions' does not work. It leads to the index page.

Github page: http://saros-project.github.io/saros/contribute/best-practices.html
Source: https://github.com/saros-project/saros/blob/master/docs/contribute/best-practices.md#classes-and-interfaces

**Comment by m273d15** [comment]
Fixed by #501
