### ISSUE TITLE
Whiteboard DH: Wrong cursor for normal lines and arrows

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#50]
Problem description
===================

When drawing lines and arrows, a little magnet (or plug?) symbol appears at the cursor. This behaviour should only occur if the lines and arrows tool was set to be magnetic.

To reproduce
============

1. Select the arrows and lines tool.
2. Switch magneticism off (if switched on).
3. Move the cursor over the canvas. The cursor grows a magnet.

Insights
========

The real magnetic cursor has another feature: When not over a connectable object, it sports a little circle with a line across to indicate that no action is possible.

Reported by: rmoehn

Original Ticket: [dpp/bugs/815](https://sourceforge.net/p/dpp/bugs/815)

**Comment by AbdBarho** [comment]
the work of Hendrik Degner never got fully integrated in the whiteboard, the magnetic arrow tool is not part of the current whiteboard.
