### ISSUE TITLE
Whiteboard DH: Selection and mouseover feedback problems with arrows and lines

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#51]
Problem description
===================

The points are probably related, therefore only one bug report:

- Arrows and lines provide no mouseover feedback, neither with the selection tool nor with the eraser.
- Arrows and lines cannot be selected with a marquee (rectangular selection).
- Arrows and lines break selection with keyboard.

To reproduce
============

1. Draw three rectangles in a horizontal line and an arrow vertically between the right two. (Like this: O O | O)
2. Mouseover feedback:
    1. Select the eraser and move the mouse over the arrow. It provides no  feedback.
    2. Select the selection tool. Move the mouse over the arrow. It provides no feedback.
3. Marquee selection:
    1. Try to select the arrow by dragging up a selection rectangle (marquee). It doesn't work.
    2. Select the rectangles by dragging up a selection rectangle. The rectangles provide mouseover feedback, the arrow doesn't. The rectangles are selected, the arrow isn't.
    3. Select the rectangles and the arrow by holding down Shift and clicking the objects. Now they can be selected together.
4. Selection with keyboard:
    1. Select the right rectangle.
    2. Push the arrow left button on the keyboard. The arrow gets selected.
    3. Push the arrow left button again. No object is selected.
    4. Delete the arrow.
    5. Select the right rectangle, again.
    6. Push the arrow left button. The middle rectangle is selected.
    7. Push the arrow left button. The left rectangle is selected.

Reported by: rmoehn

Original Ticket: [dpp/bugs/816](https://sourceforge.net/p/dpp/bugs/816)

**Comment by AbdBarho** [comment]
the work of Hendrik Degner never got fully integrated in the whiteboard, this is not a problem in the current whiteboard.
