### ISSUE TITLE
Whiteboard DH: Eraser breaks selection + DEL 

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#52]
Problem description
===================

Deleting selected objects with the DEL or Backspace key ceases to work after the eraser was used. It resumes working when you change out of Eclipse and back in again.

To reproduce
============

1. Draw some rectangles.
2. Select one and hit DEL. It disappears.
3. Select another and hit Backspace. It disappears, too.
4. Select the eraser tool and click a rectangle. It disappears.
5. Select the selection tool.
6. Click a rectangle to select it and hit DEL. It stays there.
7. Hit Backspace. The rectangle still doesn't disappear.
8. Click somewhere outside Eclipse. In another window, for example.
9. Go back to Eclipse and select a rectangle.
10. Hit DEL. The rectangle disappears.

Reported by: rmoehn

Original Ticket: [dpp/bugs/817](https://sourceforge.net/p/dpp/bugs/817)

**Comment by AbdBarho** [comment]
the work of Hendrik Degner never got fully integrated in the whiteboard, the eraser tool is not part of the current whiteboard
