### ISSUE TITLE
Saros issue labels

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#522]
Our current label set is more or less grown historically. I propose a set of labels that allow us to categorize and filter the issue easier.
All labels within a category use the same color.

## Area
Where is the issue located:
* **Area: Eclipse**
* **Area: Intellij**
* **Area: Server**
* **Area: Whiteboard**
* **Area: Infrastructure**
* **Area: Core**
* **Area: Documentation**

## Aspect
What is affected by the issue:
* **Aspect: GUI**
* **Aspect: Consistency**
* **Aspect: Follow Mode**
* **Aspect: Network**
* **Aspect: Test**

## Priority
The priority of the issue:
* **Prio: Critical**
* **Prio: High**
* **Prio: Medium**
* **Prio: Low**

## Type
* **Type: Bug**
* **Type: Feature**

## State
* **State: Unconfirmed** - Issue is opened but not analyzed by a Saros member (e.g. by reproducing the issue)
* **State: Open** - Issue is confirmed
* **State: Fixed** - Issue is resolved (closed issue)
* **State: Wontfix** - Issue will not be resolved (e.g. not reproducible, impossible to fix)
* **State: In Progress** - Someone is working on the issue

## Comply with GitHub standards
* **good first issue**
* **help wanted**

**Comment by Drakulix** [comment]
Is each section meant to be exhaustive? E.g. I do not think the `Type` section really covers all types. If we move away from our traditional title-tag-system, we should provide replacements for all types, don't you think so?

**Comment by m273d15** [comment]
I thought we should enhance this list whenever needed instead of trying to cover everything.

**Comment by stefaus** [comment]
:+1: 
I think a good addition to `Type` would be something like `Refactoring` including manual refactoring. But this wording differs from the current `Refactoring` definition in the guideline which is stating "done using automated tool support". So we would need to decide whether to change the definition or have a different name for it.
Personally, I find the limitation to automated refactoring unusual.

**Comment by m273d15** [comment]
> [...] But this wording differs from the current Refactoring definition in the guideline which is stating "done using automated tool support". So we would need to decide whether to change the definition or have a different name for it.

I think this topic is more related to our current tagging of commits. I will open an issue in order to discuss the tagging in our commit subjects.

**Comment by tobous** [comment]
@m273d15 Can this issue be closed?
