### ISSUE TITLE
Automatically share sub-modules

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#523]
Currently, the Saros logic explicitly excludes sub-modules of the shared modules (as well as their resources) from the session, meaning they will not be shared/synchronized with other participants. 

It is questionable whether this behavior was a good design choice as it leads to a default behavior that is somewhat counterintuitive. Furthermore, this restriction complicates the logic and leads to issues when creating sub-modules during a session.

All of this could be avoided by simply also sharing sub-modules when sharing a module. The sub-modules would not be picked up as modules on the receiving side automatically, but this is something that we could add later on.

**Comment by srossbach** [comment]
As you added "AdditionalProjectNegotiationData" you could add an isSubModuleOf key.

**Comment by tobous** [comment]
When thinking some more about this I discovered another problem. The IntelliJ API offers logic to obtain the module for a vitual file. But, this only gives the nearest module, meaning that, for sub-modules, the sub-module is returned instead of the parent-module. Furthermore, as the concept of sub-modules is only based on the location, I don't think this concept is known to the API. It only knows of module dependencies, which have to be specified in the module configuration (and have nothing to do with this).

This would mean that I would have to, again, do the module check by hand by comparing paths.



> As you added "AdditionalProjectNegotiationData" you could add an isSubModuleOf key.

Good idea. When allowing to share multiple modules, this could be used to automatically share all sub-modules during the project negotiation and automatically find the correct directory to map them to.

But, as this requires multiple-module-sharing, it's out of scope *for now* (but not for long). Furthermore, this still leaves the issue of how to handle such module boundaries correctly (as the current IProject impl only returns resources belonging to that module, meaning sub-modules won't be found, even if they are also shared).

**Comment by tobous** [comment]
Resolved by migration to new resource sharing model (introduced in #997; migration #998, #999, #1000, and #1001) which now shares entire resource trees independent of module boundaries.
