### ISSUE TITLE
Whiteboard DH: Diamond anchors broken

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#53]
Problem description
===================

When you connect a diamond to another object with magnetic lines or arrows and then zoom, the anchor point is not on the diamond anymore.

To reproduce
============

1. Draw an ellipse and a diamond side by side.
2. Select the connection creation (arrows/lines) tool and make it magnetic.
3. Connect the ellipse with the diamond.
4. Zoom in. The line isn't attached to the diamond anymore. Zooming out produces similar results.

Insights
========

Similar behavior was seen with panning, before. This was fixed in a rather dirty hack, commit 2215745.

Reported by: rmoehn

Original Ticket: [dpp/bugs/818](https://sourceforge.net/p/dpp/bugs/818)

**Comment by AbdBarho** [comment]
the work of Hendrik Degner never got fully integrated in the whiteboard, it is not possible to draw diamonds in the current version of the  whiteboard.
