### ISSUE TITLE
How does it compare to Atom's Teletype, Visual Studio's Live Share, Floobits, etc.?

### ISSUE THREAD

**Issue by katrinleinweber** [saros-project/saros#552]
As a potential user, I'm wondering how Saros compares to [Teletype](https://teletype.atom.io/), [Live Share](https://visualstudio.microsoft.com/services/live-share/), [Floobits](https://floobits.com/) etc. However, which technical features are the same? Which are functionally better?

From reading your docu, I get that it's more privacy-friendly if using one's own XMPP server.

Please consider adding some kind of comparison table, or an [FAQ entry](https://www.saros-project.org/documentation/faq.html). Thank you :-)

**Comment by m273d15** [comment]
Thank you for your interest in Saros.
I think creating a proper comparison matrix with an appropriate level of abstraction can be very time-consuming (searching for documentation (pricing, features), installing tools, testing tools, etc.). Therefore, I created a first PR that covers the most basic information (IDE support, OSS or commerical) which can be enhanced bit by bit.
I hope this helps.

**Comment by katrinleinweber** [comment]
Yes, thank you :-)
