### ISSUE TITLE
HashCode implementation added in #539 breaks session when module is created during project negotiation

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#649]
The new `hashCode()` implementation for `IntelliJProjectImpl` introduced in #539 breaks the Saros session when the shared module was created on the client side as part of the session negotiation.

This issue is caused by the fact that, in the process of creating a local representation of the shared module, a stub module is created to allow access to the local resources before the content of the shared module is available. When the session starts, the hash value of this stub module is used to initialize the `SharedProjectMapper`. However, this value is not updated when the module is reloaded from the received module file, which is problematic as the reload changes the hash value (since the held `Module` object is replaced).

<details><summary><i>More info on why this approach was chosen</i></summary>

When wanting to create the module as part of the project negotiation, all resources are currently zipped and transferred from the host to the client. These resources are then unpacked and written to the "local workspace". This writing to the "local workspace" (IntelliJ project) is done through the `IResource` interface. However, to create the needed `IProject` object, a local representation of the shared module is necessary. As this module does not exist yet, the logic creates a stub module. This stub module is used to create the needed `IntelliJProjectImpl` instance that is also added to the `SharedProjectMapper`. Later on, the module is reloaded from the transferred module file by the class `ModuleInitialization`. As part of reloading the module, the held `Module` object in the `IntelliJProjectImpl` instance held by the session is replaced with the new, reloaded `Module` reference.

</details>

#### Solution approach

I see two possible solution approaches (see below).

I have already implemented a prototype of solution 1. Despite that, I would still (somewhat strongly) prefer solution 2 as it seems considerably cleaner/less hacky. But solution two is still somewhat theoretical, so other problems may arise while implementing it. Attempting to use this approach is still worth it in my opinion.

##### 1. Update the `SharedProjectMapper` when reloading the module

I could add a method reloading all entries for the module in the `SharedProjectMapper` using the new hash value. This method would have to be available through the `ISarosSession` interface.
This is a **very** hacky solution as I can't use the normal collection methods to remove the entires (since they are based on the hash value, which no longer matches), meaning I have use iterators to find and remove the correct entry and the re-add it.

##### 2. Avoid the module stubbing by passing the module configuration as part of the `ProjectNegotiationData`

Instead of creating the module stub and later-on reloading the module from the transferred module file, I could instead pass the necessary information required to create the module (which currently should only be the module type; but the need for other options could arise in the future) as part of the `ProjectNegotiationData`. This would allow the logic to create the correct module from the get-got, avoiding the reload. As a result, we could remove the class `ModuleInitialization` and some code from `IntelliJProjectImpl` (e.g. the held `Module` object could be final again; the logic allowing the module object to change was iffy to begin with if it were to be called in any other circumstance than reloading the module stub; it's more of a hack to begin with).

This change would also require us to ignore module configuration files as they now no longer have to match for all participants. But, this is a change I was already considering anyways as the module configuration can theoretically also contain user configuration that is not the same for all participants. Furthermore, even though module file changes were technically "shared" with other participants with the current setup, the results of such changes were not applied to the modules of other participants as loading changes from disk to the active module require a complete module reload (as far as I know).

As this additional project data is not always needed and IDE dependent, I was thinking about a generalized approach. My current plan to extend the `ProjectNegotiationData` would be to add a new `Map<String,String>` to that is serialized and transferred as well. To fill this map, components can register properties providers that get passed an IProject object and then return two strings (key and value). These providers would then be called with the corresponding IProject object when creating a `ProjectNegotiationData` data instance to fill the map.

**Comment by tobous** [comment]
@srossbach What are your opinions on the matter?

As a general question, how is the creation of new projects as part of the project negotiation handled in Saros/E? The `AddProjectToSessioNWizard` is somewhat long and convoluted, so I had a hard time finding the logic handling this case. Could you point me towards it?

**Comment by srossbach** [comment]
The thing we do in Eclipse is broken as hell. Basically we create an empty project. During decompression the .project file is updated (Eclipse notice that and do everything). Well not everything
<projectDescription>
	<name>A</name>
	<comment></comment>

The project is displayed as: A (2) however the name in the project description is A.

See https://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fproject_description_file.html

Modifications to the project description file have mostly the same effect as changing the project description via IProject.setDescription.  One exception is that adding or removing project natures will not trigger the corresponding nature's configure or deconfigure method.  **Another exception is that changes to the project name are ignored.**

**Comment by srossbach** [comment]
I also prefer option 2. I always had issue with transmitting metadata. Normally we should not transmit related stuff like .project, everything that is in the .settings folder and maybe we should omit the .classpath file too (however if this file is setup right e.g with variables it should be shared).

The biggest problem I have is that we share file encodings "through" overwriting a special file in the .settings folder which only works in fullsharing mode, but not partial sharing.

**Comment by srossbach** [comment]
https://github.com/saros-project/saros/blob/master/eclipse/src/saros/ui/wizards/AddProjectToSessionWizard.java#L509
