### ISSUE TITLE
HTML UI is not updated when a new account is created

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#67]
It seems there is no mechanism in the de.fu_berlin.inf.pp.ui package to listen to changes in the AccountStore which could be used to update the UI via a renderer. One would expect such a mechanism in de.fu_berlin.inf.dpp.ui.core_facades.AccountStoreFacade

Reported by: bzums

Original Ticket: [dpp/bugs/855](https://sourceforge.net/p/dpp/bugs/855)

**Comment by m273d15** [comment]
Closed the issue, because we stopped working on the HTML GUI approach #682
