### ISSUE TITLE
"Finish" button of "Start Saros Configuration" is unresponsive.

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#676]
The "Finish" button on the "Configuration Complete" page of the "Start Saros Configuration..." dialog is not responsive. It does not allow the user to complete the dialog and apply the settings to the local Saros settings store.

**Comment by tobous** [comment]
@srossbach Interested in having a look at this? I am not that familiar with the Saros/E wizard implementation (even though the IntelliJ one is probably mostly a carbon copy :sweat_smile:).

**Comment by tobous** [comment]
@srossbach Never mind. I got it. Will create a PR to fix this.

**Comment by srossbach** [comment]
What is the problem, I currently testing this ?

**Comment by tobous** [comment]
Condition flipped in https://github.com/saros-project/saros/blob/master/eclipse/src/saros/ui/wizards/ConfigurationWizard.java#L201.

Weirdly enough, this seems to be an issue with the current master and something that can't be replicated on the latest release.

**Comment by srossbach** [comment]
Seems I forgot an ! 

Does not make any to create the account twice. Of course it will return null all the times at the the other statement is executed which tries to fetch a non existing account.

**Comment by duhc1** [comment]
I'm still having this issue again, just installed Saros

**Comment by jpletka01** [comment]
I'm also having this problem is there a way to fix it?

**Comment by theskyblockman** [comment]
me too
