### ISSUE TITLE
ProjectTree JSON data redundancy

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#68]
The JSON data provided by <code>/de.fu_berlin.inf.dpp.ui/src/de/fu_berlin/inf/dpp/ui/renderer/ProjectListRenderer.java</code> contains redundancies. The ProjectListRenderer provides a JSON tree representing the project structure in the workspace. However, the child of every project root is the project root itself. This "second" project root only represents the project, correctly.

Reported by: bzums

Original Ticket: [dpp/bugs/856](https://sourceforge.net/p/dpp/bugs/856)

**Comment by AbdBarho** [comment]
The current implementation does not show this redundancy.
see: [ProjectListManager](https://github.com/saros-project/saros/blob/9f686e886ee9dc6f48b83ccacefbf6b01636821e/ui/src/saros/ui/manager/ProjectListManager.java)

**Comment by m273d15** [comment]
Closed the issue, because we stopped working on the HTML GUI approach #682
