### ISSUE TITLE
Add contact which is already available leads to rename

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#69]
When you add a contact which is already in your contact list, the contact is renamed according to the name you chose while adding. Instead, there should be a prompt or so to say that the contact is already added.

Reported by: bzums

Original Ticket: [dpp/bugs/857](https://sourceforge.net/p/dpp/bugs/857)

**Comment by AbdBarho** [comment]
the patch given in https://saros-build.imp.fu-berlin.de/gerrit/#/c/2780/ is actually merged and the java part is complete.

however, the equivalent part of the error is missing from the html part

it can be simply solved by using `window.alert(errorMessage)`. is this enough, or should some other logic be triggered ?

**Comment by m273d15** [comment]
Closed the issue, because we stopped working on the HTML GUI approach #682
