### ISSUE TITLE
Color Scheme - Intellij wont load.

### ISSUE THREAD

**Issue by byCxde** [saros-project/saros#696]
If u click in the Color Scheme Tab on Saros, it wont load. Me and a friend waited 2-3 Hours and nothing changed.

1. Open Settings
2. Click on Editor
3. Slide down Color Scheme
4. Click on Saros

Normally there should be a color editor for Saros.

**Environment (please complete the following information):**
 - OS: Windows 10
 - IDE IntelliJ IDEA 2019.1.2
 - Saros Version 0.2.0

**Comment by tobous** [comment]
Hi @byCxde. Thanks for reporting the issue. I wasn't able to recreate it on Linux with IntelliJ 2019.1.3 or 2019.2.1, but I will test it with Windows as well.

In the meantime, could you provide the Saros and IntelliJ log file for the instance where the issue occurred? A description of where these files can be found is given [on our website](https://www.saros-project.org/documentation/getting-started.html?tab=intellij#report-a-bug).

**Comment by tobous** [comment]
Reproduced on Windows 10 (1903) x64 using IntelliJ IDEA 2019.2.2.

**Comment by tobous** [comment]
The issue is caused by system-dependent line separators being used for the demo text. IntelliJ IDEA always requires UNIX line separators, independently from the operating system.

I will create a patch for this and prepare a (hotfix) release.
