### ISSUE TITLE
Creating a submodule during a running session creates a desync

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#698]
When creating a submodule in a shared directory, the directory creation is send to the other participants. This is due to the base-folder for the new module being created before it is registered as a module, meaning it initially still belongs to the shared module.

This leads to a desync as, after the module is correctly registered, the directory is ignored by the Saros/I instance where the module was created. However, the directory is now present by the other participants, leading to in inconsistent state.

#### Solution Approach
Listen for module creations using the `ModuleListener` and try to prevent the sending of the initial directory creation. This could be done by manually filtering it out. This approach, however, relies on the module listener being triggered before the directory is created. If this is not the case, this approach won't be usable.

**Comment by hYdos** [comment]
is anyone going to do anything about this? this breaks lots of gradle projects

**Comment by tobous** [comment]
I am currently working on migrating the Saros resource handling from sharing modules to instead just share resource trees. This will also resolve this issue as Saros will no longer differentiate between module and sub-modules.

But this process will take some time as it requires very large and complicated refactorings.

**Comment by tobous** [comment]
Resolved by migration to new resource sharing model (introduced in #997; migration in #998, #999, #1000, and #1001) which now shares entire resource trees independent of module boundaries.
