### ISSUE TITLE
Browser-widget propagates DOM events with wrong properties

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#70]
The [which](http://api.jquery.com/event.which/) property of the jQuery event object is not computed correctly. Usually, the value should be 1, 2 or 3 wrt to the clicked button, left, middle or right. However, it is always 1, currently.

Reported by: bzums

Original Ticket: [dpp/bugs/858](https://sourceforge.net/p/dpp/bugs/858)

**Comment by AbdBarho** [comment]
There is no context to work with here.

I dont know why we need to know which mouse key is pressed, I can only assume for testing purposes.

I assume this problem resulted from the integrated jquery in the swt browser improved, Jannis has worked on the STF Tests and as far as I know he had no problems with it
