### ISSUE TITLE
Version 2.1 is not download able

### ISSUE THREAD

**Issue by byCxde** [saros-project/saros#709]
Where i can download the newest Version? :3

**Comment by tobous** [comment]
Sorry, the release is not ready just yet. We found new issues while release-testing the release 0.2.1 that we wanted to fix first. But we had already merged the website update, so we just hoped nobody would notice until we actually released the new version :wink:.

We should hopefully make the release public on GitHub tomorrow and also update the JetBrains plugin repo (but this may take longer as all new uploads have to be verified by JetBrains).

**Comment by m273d15** [comment]
The release 0.2.1 is available in [GitHub Releases](https://github.com/saros-project/saros/releases/tag/saros-intellij-0.2.1) and the Jetbrains repo version is still pending.

Sorry for the delay.
