### ISSUE TITLE
HTML Rendering of big ProjectTrees cause massive performance issues.

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#71]
The UI.Frontend get a JSON serialisation which contain the whole workspace in order to render the project entrys. However most of the times, it would be enough to only send the ProjectTreeEntrys that are currently needs to be shown in the SessionWizardManager.

This cause massiv perofrmance issuses when the workspace contain a lot files (~ >1000). See the Mailinglist for more information: https://sourceforge.net/p/dpp/mailman/message/34295134/. 

Reported by: MatthiasBohnstedt

Original Ticket: [dpp/bugs/861](https://sourceforge.net/p/dpp/bugs/861)

**Comment by AbdBarho** [comment]
I have "technically" solved this problem in #484, needs review

**Comment by m273d15** [comment]
Closed the issue, because we stopped working on the HTML GUI approach #682
