### ISSUE TITLE
task buildSearchableOptions is executed by default in intellij

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#725]
The former default behavior (before #721 ) was that the buildSearchableOptions task is skipped.
The new behavior is that the task is executed and fails. Therefore, a workaround that
disables the task is implemented.

Why is this workaround necessary?

**Comment by m273d15** [comment]
Interesting, probably it is as you assumed and the environment variable `CI` (set in travis) leads to a skipped task.

**Comment by tobous** [comment]
I was not able to reproduce this issue in Windows 10 or Linux using the downloaded version of IntelliJ (2019.3 EPA). I was not able to test this with the local version of IntelliJ as the setup no longer seems to honor `INTELLIJ_HOME`.

**Comment by tobous** [comment]
@m273d15 Can this issue be closed? The build migration to gradle plugins has already been merged and, if I remember correctly, the workaround for `buildSearcheableOptions` was removed before merging.

**Comment by m273d15** [comment]
Yes, this is fixed. :+1:
