### ISSUE TITLE
JavaScript is not always executed in HTML GUI under Windows 10

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#73]
The Saros HTML view in Eclipse is not always displayed on Windows 10 machines, meaning: the problem described below has only been observerd on Windows 10 machines so far, but not consistently.

**Symptoms:**

* The Saros HTML view in Eclipse only shows as a white area.
* A right-click in that area reveals the correct URL (e.g. `file:///F:/Development/saros/de.fu_berlin.inf.dpp.ui.frontend/html/dist/main-page.html`) and correct loaded content (same as [de.fu_berlin.inf.dpp.ui.frontend/html/main-page.html](https://github.com/saros-project/saros/blob/master@%7B2016-01-27%7D/de.fu_berlin.inf.dpp.ui.frontend/html/main-page.html)). It looks like the Javascript which should replace the `div#Saros` node is not executed, which is supported by the failure to execute even the simplest JavaScript (see first comment below).
* Opening the `dist/main-page.html` file in Mozilla Firefox and Microsoft Edge results in a properly rendered UI.
* Opening it in Microsoft Internet Explorer requires to allow the execution of "active contents" on the local machine.
* The behavior in Eclipse is the same with our without MS IE installed.

Reported by: fzieris

Original Ticket: [dpp/bugs/864](https://sourceforge.net/p/dpp/bugs/864)

**Comment by fzieris** [comment]
Tried again, works fine now.
