### ISSUE TITLE
Extending User Permissions

### ISSUE THREAD

**Issue by Memo2109** [saros-project/saros#731]
My job is to come up with an extension of the User Permissions mechanism. I've seen there is already a somewhat flexible Permission implemented in the User Class:

https://github.com/saros-project/saros/blob/master/core/src/saros/session/User.java#L35

My question: What would you like specifically to be extended? Are there use cases for currently missing functionality? The only problem i could find until now is the missing Permission for Users to upload documents into the Session. From my point of view it would be sufficient to add a specifier to the enum Permissions and an instance method like hasShareDocumentPermission()..?

**Comment by srossbach** [comment]
This an issue tracker not a discussion platform. Please use the Gitter channel or ask @m273d15 for further questions.
