### ISSUE TITLE
Goodbye XMPP, hello ...?

### ISSUE THREAD

**Issue by Memo2109** [saros-project/saros#732]
I've been told by @m273d15 that the XMPP functionality is supposed to disappear from Saros. I am currently searching for a way to authenticate existing Users at the Super Server. My preferred solution would be to employ existing user credentials, like XMPP login/password. Is there a way to learn more about saros upcoming protocol?

**Comment by srossbach** [comment]
This an issue tracker not a discussion platform. Please use the Gitter channel or ask @m273d15 for further questions.

**Comment by m273d15** [comment]
Ääähm this might be a misunderstanding. The xmpp protocol might be substituted in the far future. It is nothing you have to worry about. More discussion in Gitter
