### ISSUE TITLE
Update to: Gradle 6

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#768]
The new gradle version 6.0.1 is [released](https://docs.gradle.org/6.0.1/release-notes.html).
In order to stay up-to-date we should check whether we are still compatible and test:
- [ ] Integration with eclipse
- [ ] Integration with IntelliJ
- [ ] Builds on CLI
- [ ] STFs

**Comment by tobous** [comment]
As part of the upgrade to gradle 6, we will also have to update the gradle build scan plugin. The update instructions can be found here: https://docs.gradle.com/enterprise/gradle-plugin/#upgrading_to_gradle_6
