### ISSUE TITLE
Inconsistency notification after file deletion and re-creation with different content

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#775]
Currently, the `ConsistencyWatchdogServer` does not actively get notified when a file is deleted. Furthermore, for some Saros implementations (like Saros/E), new files with initial default content (like package and class declarations) are created with this content already being part of the document, meaning this initial content is transferred as part of the file creation activity.

This leads to a situation where a file is deleted and re-created before the checksum is checked again (as this only happens periodically every 10 seconds). In such cases, the checksum will not be seen as dirty, even though the file content has changed. This outdated checksum is then send to the clients, which read the correct new content from disk, leading to an erroneous desync detection.

This desync is automatically resolved after a participant modified the file and the checksum is re-calculated.

#### Steps to reproduce

The re-creation of files during a session is only possible with the PR #714.

- Alice and Bob create a session.
- Alice deletes a shared file.
- Alice quickly re-creates the shared file (with different initial content).

##### Expected behavior
- Everything is detected as consistent.

##### Actual behavior
- A desync notification is triggered for the non-host participant.

**Comment by tobous** [comment]
A good solution would be to mark the checksum as dirty when the file is deleted on the host side. The only issue I have with this is how to tell the `ConsistencyWatchdogServer`. The only currently used listener is the `ISharedEditorListener`. Even though a `fileDeleted()` method could theoretically be added to the interface, it does not match its general purpose.

I am somewhat torn on how to handle this. It is a corner-case issue (file deletion and re-creation with a new content in a 10 second window) that is resolved automatically when the users modify the editor.

I am currently leaning towards just leaving this bug open as the only fix I could see for this would include the addition of a lot of other logic (and possible the introduction of a new listener that is only used for this case).

@m273d15 @srossbach What is your opinion on the matter? Is this an acceptable corner case bug?

@srossbach Do you have a better idea on how to notify the `ConsistencyWatchdogServer` of a file deletion/re-creation (as part of the core logic)?

**Comment by srossbach** [comment]
It is current possible to hook you into every component and then listen for the activities they are generating. As this is not possible because the implementors that are generating the activity are not present in the core a dirty hack would to be an option. Add the possibility to add a sniffer (please deprecate this method as default) that sniff for every generated activity. Now you could listen to the activities you are interested in.

**Comment by tobous** [comment]
> Add the possibility to add a sniffer (please deprecate this method as default) that sniff for every generated activity.

Yeah but I still don't think that it is worth it to introduce such a large workaround for a minor corner-case issue. What do you think?

**Comment by srossbach** [comment]
I guess it is fine having this issue as it seldom happens and does not cause any problematic issues at all.

**Comment by tobous** [comment]
As discussed above, the fix for this issue introduces to much otherwise unnecessary code and requires many workarounds. Since the issue only happens in rare corner cases, resolves itself, and has (almost) no negative impact on the session (besides a false-positive inconsistency notification), I marked this as 'Wontfix'.

If, however, anyone actually takes issue with this decision (i.e. finds a case where this issue has more impactful consequences or happens more frequently) and/or can suggest a better way of fixing it (avoiding the workarounds), I am (or rather the team is) more than happy to discuss this issue again and re-open it if appropriate.
