### ISSUE TITLE
Building the Saros/I plugin as a zip fails

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#78]
Building the plugin as a zip file using the option "Prepare Plugin Module 'de.fuberlin.inf.dpp.intellij' For Deployment" fails with the message "duplicate entry: META-INF/MANIFEST.MF".
The problem seems to be /de.fu_berlin.inf.dpp.ui.frontend/bin/META-INF/MANIFEST.MF. This file is created every time the project is (re-)build in IntelliJ trough the option "Build">"Rebuild project". Removing this MANIFEST.MF allows the zip to be build.

Reported by: tobous

Original Ticket: [dpp/bugs/885](https://sourceforge.net/p/dpp/bugs/885)

**Comment by koppor** [comment]
I "solved" this issue by applying the proposed workaround: Remove ` /de.fu_berlin.inf.dpp.ui.frontend/bin/META-INF/MANIFEST.MF` (after building the plugin with intellij).

**Comment by tobous** [comment]
I don't know what you mean by "solved". But I probably was not clear enough when saying "(re-)build". What I meant was that the file gets re-created when the option "Rebuild project" in the "Build" menu is chosen. This is still happening for me with IntelliJ 2018.1.

I updated the description to avoid future confusion.

Does the issue persist for you when selecting "Rebuild project"?

**Comment by koppor** [comment]
I just did the step-by-step howto at http://www.saros-project.org/saros-for-intellij/dev-environment. Then, I encountered the above issue. I deleted `/de.fu_berlin.inf.dpp.ui.frontend/bin/META-INF/MANIFEST.MF` to move fowarded.

As soon as IntelliJ does not crash at startup and the saros project any more, I'll report back regarding "Rebuild project".

**Comment by tobous** [comment]
The tutorial was way out of date as I did not get around to re-writing it (there is only so much time in a day). Sorry. I am currently updating it so that it contains the right instructions/does not actively instruct people to do wrong things. I will update you when I'm done (should not take longer than half an hour.)

**Comment by tobous** [comment]
I wrote a short summary of the changes in the tutorial in #89. The tutorial now also contains the information about the superfluous META-INF to avoid confusion in the future.

**Comment by tobous** [comment]
No longer applicable since we are using gradle as our build tool now.
You can find a description on how to set up the development environment and build via gradle on http://saros-project.github.io/saros/contribute/development-environment.html.
