### ISSUE TITLE
Replace IPath with the usage of java.nio.file.Path

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#797]
`IPath` seems like an unnecessary implementation for a feature that is already provided by the default java libraries. For Saros/E, this isn't an issue as it is mainly a wrapper for the Eclipse `IPath` implementation, but for other IDEs this requires a separate implementation. This could theoretically also be "solved" by implementing the `IPath` implementations using `Path` for the other IDEs, but using Path directly in all cases seems more sensible to me as it removes an unnecessary level of abstraction and reduces unnecessary code overhead.

Most methods defined in [`IPath`](https://github.com/saros-project/saros/blob/master/core/src/saros/filesystem/IPath.java) can be directly replaced by a corresponding method in `Path`, the only outliers requiring some (minor) work being `toPortableString()` and `toOSString()` (from what I can tell).

Since this is a central part of the implementation, it should also be tested along the way that the move to using `Path` does not introduce any unintended side effects or changes the behavior of the logic. The [STF](https://www.saros-project.org/contribute/saros-testing-framework.html) should be a good starting point for this.

**Comment by srossbach** [comment]
I do not know the Java Path API internals but looking at the Server code (and I guess the IntelliJ one is just a copy) then the toPortableString implementation is already broken.

Assuming we are using absolute paths (that we do not use at all)

Sending from Windows ```C:\FOO\BAR``` will translate to ```C:/FOO/BAR``` on Unix
While it is a valid path name on Unix the correct result would be to throw an exception as Unix does not have device letters.

Sending from Unix ```C:/FOO\BAR" (2 segments, C: , FOO\BAR" will translate to ```C:\FOO\BAR``` on Windows
The first segment is a drive letter on the Windows side which is wrong
The second segment splits into two segments foo and bar.

Source of the Eclipse Path implementation which is about 1k LOCs mainly handling these issues.

https://github.com/eclipse/rt.equinox.bundles/blob/master/bundles/org.eclipse.equinox.common/src/org/eclipse/core/runtime/Path.java

**Comment by tobous** [comment]
Yeah, but on the other hand, creating "portable" versions of absolute paths does not make sense for our use case anyways as it is *very* unlikely that they will be usable for other clients.

So the easiest solution in my opinion would be to require the path to be relative for the `getPortablePath()` method to function and return `null` or throw an exception otherwise.

And edge cases such as segmented paths should be cought by the CTOR/factory method. As we have full control over the usage, such restrictions should not be too big of an issue.

**Comment by srossbach** [comment]
```C:/FOO\BAR``` is a relative path on a Unix system. My guess is that it will already be dropped on Windows systems stating that the path is absolute. The correct error message would be that this is not a valid relative path on the current file system.
