### ISSUE TITLE
IntelliJ/Eclipse cross-IDE session

### ISSUE THREAD

**Issue by PyvesB** [saros-project/saros#801]
Hello Saros team!

One of my colleagues is using IntelliJ and I'm using Eclipse. We tried initiating a Saros session, however, the following error message was displayed:

> Invitation was canceled locally because of an error: The Saros plugin of XXX (Version 0.2.1) is not compatible with your installed Saros plugin (Version 15.0.0)

The Readme seems to imply this is possible: "Each [participant] can work in their usual IDE". Is this a bug or is cross-IDE support actually not yet implemented?

Thanks in advance!

**Comment by tobous** [comment]
Cross-IDE is not yet implemented. We are actively working on it, but it will still take a while.
