### ISSUE TITLE
Eclipse choose Workspace Location isnt opening

### ISSUE THREAD

**Issue by ChickenCoderYt** [saros-project/saros#804]
**Describe the bug**
If I share a project with the server and i invite someone the server sas waiting for the contact to choose location where the project should be saved.
But at client site the Choose project location does not pop up

if i have two accounts connected with the server and one of them shares a project the pop up also doesnt open

**To Reproduce**

1. I run the server by following command:
`java -Dsaros.server.interactive=yes -Dsaros.server.workspace=C:\Users\User\Desktop\SarosServer\workspace -Dsaros.server.jid=javacodingserver@saros-con.imp.fu-berlin.de -Dsaros.server.password=MyPassword -jar Server.jar`

2. After the Server booted i entered command: `share McTd`

> ### Server response:

```
DEBUG 14:48:07,516 [main] (SharedProjectMapper.java:134) added project saros.server.filesystem.ServerProjectImpl@195686ac with ID 1612562064 [completely shared:true]
Command 'share McTd' is not known. (Type 'help' for available commands)>
```
3. I entered command to invite myself: `invite Huhngut@saros-con.imp.fu-berlin.de`

> ### Server response:

```
[\] Waiting for huhngut@saros-con.imp.fu-berlin.de to accept invitation...
```
4. next i accepted the invite:

> ### Server response:

```
[ 0%] Creating file list and calculating file checksums. This may take a while... - McTd: .git/logs/refs/remotes/origin/master
DEBUG 14:55:31,899 [saros-ServerProjectNegotiation-0] (AbstractOutgoingProjectNegotiation.java:190) OPN [remote side: huhngut@saros-con.imp.fu-berlin.de/Saros] : sending file list
DEBUG 14:55:32,013 [saros-ServerProjectNegotiation-0] (AbstractOutgoingProjectNegotiation.java:224) OPN [remote side: huhngut@saros-con.imp.fu-berlin.de/Saros] : waiting for remote file list
[-] Waiting for huhngut to choose project(s) location -
```
5. At My Eclipse nothing popped up to choose the location:

**Expected behavior**
I expected that a window opens that asks me if i want to create a new project or use a existing one
like it happens when i invite someone using saros and not the server

**Log files**

[EclipseLog.txt](https://github.com/saros-project/saros/files/4040718/EclipseLog.txt)
[Saros_huhngut@saros-con.imp.fu-berlin.de_2020-01-09_15-06-46.log](https://github.com/saros-project/saros/files/4040719/Saros_huhngut%40saros-con.imp.fu-berlin.de_2020-01-09_15-06-46.log)
[Saros-Errors_2020-01-09_15-06-46.log](https://github.com/saros-project/saros/files/4040720/Saros-Errors_2020-01-09_15-06-46.log)
[ServerLog.txt](https://github.com/saros-project/saros/files/4040785/ServerLog.txt)

**Screenshots**
![EclipseView](https://user-images.githubusercontent.com/55546882/72074286-ef35a980-32f1-11ea-8667-8cd264e871e1.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - IDE [e.g. Eclipse 2019-06
 - Saros Version 15.0.0

**Additional context**
In the Log File is an error

**Comment by tobous** [comment]
@Drakulix Could you have a look at this?

**Comment by srossbach** [comment]
ERROR 15:07:18,447 [DispatchContext] (XStreamExtensionProvider.java:300) unmarshalling data failed
com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field saros.negotiation.ProjectNegotiationData.additionalProjectOptions
---- Debugging information ----
message             : No such field saros.negotiation.ProjectNegotiationData.additionalProjectOptions
field               : additionalProjectOptions
class               : saros.negotiation.ProjectNegotiationData
required-type       : saros.negotiation.ProjectNegotiationData
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /pnof/payload/projectNegotiationData/PJNGDATA/additionalProjectOptions
line number         : 1
class[1]            : java.util.ArrayList
converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[2]            : saros.communication.extensions.ProjectNegotiationOfferingExtension
class[3]            : saros.misc.xstream.XStreamExtensionProvider$XStreamPacketExtension
version             : 1.4.10
-------------------------------

**Comment by srossbach** [comment]
Guess you compiled the the server against the actual master and used an older incompatible version.

@tobous can you look at the issue. It seems that XStream is throwing exception for fields that cannot be assigned.

This leads to the problem where an older version could send data to a newer version but not vice version, i.e the field will be null when sending a packet from "old" to "new" but sending from "new" to "old" will throw an exception.

**Comment by ChickenCoderYt** [comment]
> 
> 
> Guess you compiled the the server against the actual master and then used an older incompatible Saros Eclipse version.
> 
> @tobous can you look at the issue. It seems that XStream is throwing exception for fields that cannot be assigned.
> 
> This leads to the problem where an older version could send data to a newer version but not vice versa, i.e the field will be null when sending a packet from "old" to "new" but sending from "new" to "old" will throw an exception.

I dont understand I have the newest version of saros in eclipse 15.0.0

**Comment by tobous** [comment]
> I dont understand I have the newest version of saros in eclipse 15.0.0

@ChickenCoderYt Well yes, you have the newest *release*, but it has been a while since version `15.0.0` has been released and a lot has been happening internally since then. So the incompatibility stems from you using the Server version based on the current master (which still has the version `15.0.0`; that is kind of confusing; sorry) and the Saros/E version based on the current release `15.0.0`.

**So in short, you should be able to resolve the issue by building Saros/E and the Saros Server from the master (preferably from the same commit) and then using those versions.**

To avoid confusion in the future, we should add a "devel" modifier to the version for developer builds.

>This leads to the problem where an older version could send data to a newer version but not vice versa, i.e the field will be null when sending a packet from "old" to "new" but sending from "new" to "old" will throw an exception.

@srossbach I am not sure if there is anything I can do about that, but I will have a look.

This would always be an issue when changing anything xStream related (like adding or removing a parsed component).

But this specific breakage of version compatibility can possibly be avoided simply by removing the added parsed fields again. The field `additionalProjectOptions` were only added to better support module creation/adjustment on session start. But, with the move away from module support and towards simply sharing "content roots", this will probably no longer be necessary. But I will have to think about it more before I can be certain on that.

**Comment by ChickenCoderYt** [comment]
Thanks Im trying to build the Version by my self
