### ISSUE TITLE
Saros/I reads keyboard input in menus

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#81]
Saros/I reads the keyboard inputs while the user is focusing the IntelliJ interface (e.g. while typing in the refactoring->rename textfield). Activities for these inputs are created but locally thrown out before sending as the given path in the activity is NULL.

Reported by: tobous

Original Ticket: [dpp/bugs/893](https://sourceforge.net/p/dpp/bugs/893)

**Comment by tobous** [comment]
As we are already filtering for such events, this is not a problem.
