### ISSUE TITLE
Saros/I creates file activities during file synchronization

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#82]
I already added a hack that the activities are at least not fired, but this behavior is.

1. Unwanted because it lenghten the synchronization process
2. May result in an OutOfMemoryError depending on the file size of a file 

Reported by: kargor

Original Ticket: [dpp/bugs/895](https://sourceforge.net/p/dpp/bugs/895)

**Comment by tobous** [comment]
Superseded by #993.
