### ISSUE TITLE
Changing XMPP accounts during a session freezes/blocks the IDE for 

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#821]
When reconnecting with another XMPP account, the state of the plugin, i.e. the current connection and any running sessions, is not cleaned up correctly.

As a result, a user trying to reconnect with another account during a session will result in the IDE being blocked by the connection widget for up to 30 seconds.

This can be avoided by ending any running session and disconnecting before connecting to the new account.

**Comment by srossbach** [comment]
The "30 seconds" do not help that much. You already  know the problem so why do you not describe it. It could be 5 seconds, 30 seconds or 10 minutes depending on how much waiting time is spent in each session component that wants to shutdown in a way that is causing an issue in such that timeouts will occur if you disconnect / stop a session if a modal dialog is present in the IntelliJ IDE during the session stop.
