### ISSUE TITLE
Cannot build Saros v15.0.0, failed mavenizeP2Repository_1 (Ambiguous method overloading for method java.io.File)

### ISSUE THREAD

**Issue by johnpanos** [saros-project/saros#827]
**Describe the bug**
After cloning version 15.0.0 and trying to run prepareEclipse, the build fails due to Ambiguous method overloading for method java.io.File.

**To Reproduce**
1. Open your terminal
2. Run `git clone --branch saros-eclipse-15.0.0 https://github.com/saros-project/saros.git --depth 1`
3. Run `cd saros`
4. Run `./gradlew prepareEclipse`

**Expected behavior**
The expected behavior is for gradle to produce saros jar files for use in Eclipse by dropin.

**Log files**
```
~/Documents/saros
❯ ./gradlew prepareEclipse
> Task :mavenizeP2Repository_1 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mavenizeP2Repository_1'.
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.net.URI]
        [class java.lang.String]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
6 actionable tasks: 6 executed

Publishing build scan...
https://gradle.com/s/oxuic4eutrymm
```

**Screenshots**
![image](https://user-images.githubusercontent.com/25217527/73605106-fb0e3780-454e-11ea-9f6b-55dd66418fc9.png)

**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15 (Build 19A602)
 - IDE: N/A, Command Line
 - Saros Version 15.0.0

**Comment by tobous** [comment]
The release branch `saros-eclipse-15.0.0` still runs on our old build system. As we did not have any good way of accessing Eclipse artifacts, it required a local Eclipse installation.

The guide for the necessary setup is given on the old version of our documentation:
https://github.com/saros-project/saros/blob/saros-eclipse-15.0.0/docs/contribute/development-environment.md (see section ["Common"](https://github.com/saros-project/saros/blob/saros-eclipse-15.0.0/docs/contribute/development-environment.md)).

Out of curiosity: Is there a particular reason why you are interested in building the old release branch?

**Comment by tobous** [comment]
@johnpanos If you are still having issues related to the mentioned topic, please reply giving more information. Otherwise, I am going to close this issue as resolved next Monday (the 24th of February).
