### ISSUE TITLE
Deleting a file during a session leads to the client becoming unsynchronized

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#83]
If a file is removed during a session, the file is also removed from the session on the other side. After that, the other Saros/I client perceives the local contents, specifically the deleted file, to have become unsynchronized. Attempts of re-establishing the synchronization fail as an exception is logged stating that the file that is supposed to be removed was not found.

Reported by: tobous

Original Ticket: [dpp/bugs/897](https://sourceforge.net/p/dpp/bugs/897)

**Comment by tobous** [comment]
Fixed with #277 and #307.
