### ISSUE TITLE
Saros/I build artifact contain duplicate library jars

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#830]
When looking at the [Saros build artifacts](https://github.com/m273d15/saros/actions/runs/38825739), I noticed that the artifact for Saros/I is considerably larger than the one for Saros/E or the Saros Server (8mb vs 5mb).  

This seems to stem from many libraries (like XStream, Smack, Commons libraries, our re-packaged picocontainer, etc.) being included twice. Once in the general zip and once in the contained `saros.core.jar`.

This isn't a huge issue as 8mb still isn't much, but it would still be nice to avoid such duplication.

**Comment by m273d15** [comment]
We have to avoid the additional jars in the `saros.core.jar`. Therefore, we need to introduce two different core jars (Saros/E and Saros/I are currently using the same core jar).
