### ISSUE TITLE
Wizard "Add Projects" allows an empty field when choosing the option "Use existing project"

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#86]
When accepting a session with Saros/I, the user can either choose to create a new project or to use an existing project. If this option is chosen by selection "Use existing project", the field titled "Project name" is initially empty but the user still has the option to continue the wizard by clicking on the "next" button.
If the wizard is continued in this state, the project negotiation is aborted as the local representation of the module could not be found.

If something else is entered in the field (either by entering it manually or by selecting a folder with the "Browse" button) the "Next" button is grayed out. This This would suggest to me that there already is a check in place but that it is not executed when a different option is chosen. This behavior also holds true when selecting the "Create new project" option when the next button is grayed out as the entered name has to be adjusted (for example by adding and then removing a character) to re-enable the next button.

**Steps to reproduce:**
When invited to join a session:
1. On the first window of the wizard, click "Next" to accept the session Invitation.
2. On the second window (titled "Add Projects"), select the option "Use existing project".
3. Click on the "Next" button.

Reported by: tobous

Original Ticket: [dpp/bugs/900](https://sourceforge.net/p/dpp/bugs/900)

**Comment by tobous** [comment]
Fixed by da2f22bca50d771f6b38f7a4bb57b07cd092f298. Wizard now checks the newly chosen text field after a switch.
