### ISSUE TITLE
Add help on "cobertura.dir" to the build instructions

### ISSUE THREAD

**Issue by koppor** [saros-project/saros#89]
I followed http://www.saros-project.org/saros-for-intellij/dev-environment and solved https://github.com/saros-project/saros/issues/78. Now, I am stuck at the step with ant:

```
> ant plugin.bundle.zip.saros-i
Buildfile: d:\git-repositories\saros\de.fu_berlin.inf.dpp.intellij\build.xml

BUILD FAILED
d:\git-repositories\saros\de.fu_berlin.inf.dpp.intellij\build.xml:254: d:\git-repositories\saros\de.fu_berlin.inf.dpp.intellij\${cobertura.dir} does not exist.

Total time: 0 seconds
```

I did not find a quick way to solve this issue. When deleting that task, I get 

    d:\git-repositories\saros\de.fu_berlin.inf.dpp.intellij\build.xml:237: taskdef class com.intellij.ant.Javac2 cannot be found

Maybe, it is because I am using the 2018 version of IntelliJ.

**Comment by fzieris** [comment]
Hm, could indeed be due to a change in IntelliJ's utils.
@tobous Which IntelliJ version do you currently work with?

Concerning #78 : Could you provide some details as to how you solved it as a comment in that issue? Thanks!

**Comment by tobous** [comment]
I am currently using the IntelliJ version provided by my package manager (Intellij 2018.1.1).

I never got the ant build running on my side either. It is dependent on to many things only needed for the server build (like cobertura) and I did not know how to make ant dependencies optional (if that is even possible). Furthermore, the ant job is not configured in IntelliJ, meaning that the correct paths and configs are not provided by default. The whole build.xml probably needs an overhaul as it is currently only suited for our server builds. I added a note to the tutorial that the ant build is not configured correctly/does not work.

It was not big enough of an issue to invest a lot of time into it as the builds with IntelliJ still work (even though removing the META-INF folder gets annoying).

**Comment by tobous** [comment]
@koppor As I mentioned in #78, I updated the tutorial. The big changes are:
- You should use the branch "release/intellij-0.1.0" as it is currently more stable for Saros/I.
- You should not remove any libraries from the project sdk. This is especially important as Saros/I depends on the xStream version provided by IntelliJ. I would suggest just removing the old project sdk and adding a new one. There are no changes necessary (except for the renaming to "IDEA SDK").
- If you want to import the IntelliJ sources, you should check out the correct build. (See number 7. of the project sdk setup).
- You don't have to copy the swt_plugin to the plugin folder. I don't know what it was supposed to be needed for, but I never did it and did not experience any problems (and can't see any difference after doing it). This might just be an artifact of an old setup.

**Comment by tobous** [comment]
It is also important to use a current version of IntelliJ as I don't know how far IntelliJ's backwards compatibility goes. But since you are using a 2018 version, this should not be a problem.

**Comment by fzieris** [comment]
@tobous the `swt_plugin` is necessary for the HTML GUI. We rely on the SWT browser which is not part of Swing (obviously) and therefore need to ship 6 variants of SWT.

**Comment by tobous** [comment]
Ok, I removed the note from the tutorial.
But now I am wondering: How are we supposed to deploy the plugin with the HTML GUI if there is another component that needs to be added by hand before the plugin is usable? Or is the swt_plugin contained in the plugin bundle and extracted to the correct folder automatically?

**Comment by fzieris** [comment]
At least for Eclipse update sites, there is a dependency system: Even if you don't select the Saros/Core explicitly, it will be downloaded and installed.
[IntelliJ plugins also can have dependencies](https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_dependencies.html), so we would simply deploy two plugins: One under GPL and another under EPL.

**Comment by tobous** [comment]
No longer applicable since we are using gradle as our build tool now.
You can find a description on how to set up the development environment and build via gradle on http://saros-project.github.io/saros/contribute/development-environment.html.
