### ISSUE TITLE
Removing color editing

### ISSUE THREAD

**Issue by illuminator3** [saros-project/saros#903]
How do you remove the color editing when someone writes code that you, yourself didn't write? (For example if someone else writes a piece of code it's white for me)

**Comment by tobous** [comment]
This is generally not the place to ask questions but rather to report issues with the plugin. Questions regarding the usage of Saros can be asked on our [user gitter](https://gitter.im/saros-project/saros/user) or [user mailing list](https://groups.google.com/forum/#!forum/saros-user).

Regarding your question: You have to be a bit more specific. Are you using Saros for Eclipse or Saros for IntelliJ?

**For Saros for IntelliJ**, the color settings are described in the ["Getting Started" section of our website](https://www.saros-project.org/documentation/getting-started.html?tab=intellij#changing-user-colors).

**For Saros for Eclipse**, the highlighting can be adjusted in the Eclipse settings. You can modify them by changing the entries starting with "Saros" in `"General" > "Editors" > "Text Editors" > "Annotations"`. The different annotation types are described [here](https://www.saros-project.org/documentation/screenshots.html?tab=eclipse).
