### ISSUE TITLE
Core Test UPnPTest#testDispose() Fails if Assertions are Enabled

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#98]
When running the Saros core test suite with assertions enabled, the test UPnPTest#testDispose() fails with an assertion error:
<pre>
java.lang.AssertionError
	at de.fu_berlin.inf.dpp.net.upnp.internal.UPnPServiceImpl.createPortMapping(UPnPServiceImpl.java:168)
	at de.fu_berlin.inf.dpp.net.UPnPTest.testDispose(UPnPTest.java:163)
</pre>

### Steps To Reproduce:
1. Enable assertions (include "-EA" in your vm options for the core test runconfig)
2. Run the core test suite (de.fu_berlin.inf.dpp.SarosCoreTestSuite)

**Comment by m273d15** [comment]
Enable assertions during build process after this issue is fixed.
